/* 전략기획실 대시보드 데이터 — 이 파일만 고치면 화면이 바뀝니다.
   stage : idea(아이디어) · prep(준비중) · planning(기획중) · planned(기획완료·검토대기) · applying(적용중) · done(적용완료) · dropped(폐기·보류)
   decision : 대기 · 수락 · 확정 · 보류 · 폐기
   docs[].type : md(대시보드 안에서 바로 읽음) · html(새 창) · link(외부)
   갱신: 2026-09-04 (기술참모) */
window.PLAN = {
  updated: "2026-09-05 (최종 실행안)",
  stages: [
    { key: "idea",     label: "아이디어",        hint: "제안만 있음. 조사·검토 전" },
    { key: "prep",     label: "준비중",          hint: "사실 조사·사전 준비 진행" },
    { key: "planning", label: "기획중",          hint: "기획서 작성·갈고 있는 중" },
    { key: "planned",  label: "기획완료",        hint: "회장님 검토·결정 대기" },
    { key: "applying", label: "적용중",          hint: "클코팀장(클로드코드) 작업 중" },
    { key: "done",     label: "적용완료",        hint: "프로덕션 반영 또는 결정 확정" },
    { key: "dropped",  label: "폐기·보류",       hint: "안 하기로 했거나 뒤로 미룸" },
  ],
  areas: ["제품", "인프라", "운영", "영업·가격", "법무·정책", "프로세스"],
  ideas: [

    /* ───────────── 적용중 ───────────── */
    {
      id: "inquiry", title: "견적 문의 접수 — DB 저장 + 사장님 알림", stage: "applying", area: "제품", decision: "확정",
      owner: "클코팀장", since: "2026-09-02", updated: "2026-09-04",
      summary: "손님이 30초 안에 사진 3장·연락처를 남기면 사장님 폰에 60초 안에 문자·이메일이 오고, 에디터 문의함에 쌓인다. 지금은 전화 링크 카드뿐이라 문의가 남지 않는다.",
      why: "무료 체험 한 달 안에 '문의가 왔다'를 경험하지 못하면 결제 전환이 0에 가깝다. P5(결제) 진입 조건 1번.",
      status: "G1·마이그레이션·G2 전부 완료, 프로덕션 라이브. 참모 확인(2026-09-04): 발행 사이트에 실제 폼 렌더(연락처·내용·사진 3장·동의·전화 버튼), 에디터 문의함 탭(칩 필터·빈 상태 문구·?tab=inbox 기본), /api/admin/notify-check = 문자·이메일 채널 모두 켜짐·INQUIRY_SALT 설정됨·24시간 접수 3건·알림 실패 0건. 마이그레이션은 core 중복을 피해 alter 로 작성되었고 익명 insert 정책(누구나 무제한 접수 가능하던 구멍)도 함께 제거됨.",
      next: "남은 확인 1건 — 실제 접수된 문의가 문의함에서 사진(10분 signed URL)까지 표시되는지 회장님 눈으로 1회. 그 뒤 이 항목은 적용완료.",
      docs: [
        { label: "견적 접수 스펙 (inquiry.md)", href: "/plandept/docs/inquiry-spec-2026-09-03.md", type: "md" },
        { label: "실행 순서 — 견적 접수 먼저 (STEP 0~4)", href: "/plandept/docs/inquiry-first-serial-2026-09-03.md", type: "md" },
        { label: "실행 런북 · 견적 접수 설계 (리포트)", href: "/plandept/docs/runbook-inquiry-2026-09-03.html", type: "html" },
      ],
      history: [
        { d: "2026-09-02", t: "기술고문 리포트에서 '결제보다 문의 접수 먼저' 권고" },
        { d: "2026-09-03", t: "P5 진입 조건으로 확정, 스펙 저장소 커밋" },
        { d: "2026-09-04", t: "G1 완료, 브랜치 병합 진행" },
        { d: "2026-09-04", t: "db push(alter) → G2 완료 → 프로덕션 라이브. 참모 확인: 폼·문의함·알림 채널 정상" },
      ],
    },
    {
      id: "r2", title: "이미지 저장소 Cloudflare R2 이전", stage: "applying", area: "인프라", decision: "확정",
      owner: "클코팀장", since: "2026-09-03", updated: "2026-09-04",
      summary: "사진·영상은 R2(전송량 무료), DB·로그인은 Supabase 유지. 앱은 lib/storage.ts 한 곳만 안다. R2-1(신규 업로드) → R2-2(기존 638장 백필).",
      why: "Supabase Free는 전송 5GB/월, Pro도 250GB 뒤 과금. 사진·영상이 늘고 방문이 몰릴수록 차이가 커진다.",
      status: "DNS Cloudflare 이전·버킷 2개·img.onstori.com·env 6개 완료. R2-1 코드 완료(feat/r2-1-storage 병합 중). R2-2는 스프린트 7번.",
      next: "병합 후 프로덕션에서 업로드 URL이 img.onstori.com/… 인지 확인. R2-2는 dry-run 후.",
      docs: [
        { label: "R2 이전 스펙 (storage-r2.md)", href: "/plandept/docs/storage-r2-spec-2026-09-03.md", type: "md" },
      ],
      history: [
        { d: "2026-09-03", t: "회장님 제안 → 참모 검토 → 채택. 문의 접수보다 앞에 배치" },
        { d: "2026-09-03", t: "네임서버 이전·버킷·토큰·env 완료 (참모 코칭)" },
      ],
      side: "발견: Cloudflare 이전 후 *.onstori.com 와일드카드 레코드가 없어 옛 서브도메인 링크의 301이 DNS 단계에서 죽음 → 별도 아이디어 'wildcard' 참조.",
    },

    {
      id: "plandept", title: "전략기획실 대시보드 — onstori.com/plandept (운영자 전용)", stage: "done", area: "프로세스", decision: "확정",
      owner: "기술참모(파일) · 클코팀장(배포)", since: "2026-09-04", updated: "2026-09-04",
      summary: "아이디어를 단계별(아이디어→준비중→기획중→기획완료→적용중→적용완료/폐기)로 보고, 기획서·샘플을 그 자리에서 읽는 대시보드. content/plandept/ 에 두고 라우트 핸들러가 운영자 쿠키(ADMIN_KEY)를 확인한 뒤 파일을 내준다. 사업 설계서(/onstoriplandept)도 같은 방식으로 잠김.",
      why: "회장님이 외부에서도 아이디어를 검토하고, 클코팀장·참모가 같은 목록을 본다. 폐기된 것도 이유와 함께 남아 같은 논의를 반복하지 않는다.",
      status: "적용완료(00acf40). 로그아웃 상태에서 /plandept·/onstoriplandept·문서 경로 전부 운영자 인증 화면으로 이동(참모가 별도 브라우저로 확인), 로그인 상태에서 보드·해시 주소·md 렌더 정상(참모가 크롬으로 확인). 발견: /onstoriplandept 는 빌드 생성물(scripts/build-plandept.ts)이라 OUT_DIR 을 content/ 로 바꿔 잠금이 유지되게 함. 로그인 후 원래 주소 복귀 + 오픈 리다이렉트(//) 차단.",
      next: "운영: 아이디어 갱신은 content/plandept/data.js(참모 배치) → commit/push. 예약 슬러그 'plandept' 마이그레이션은 다음 db push 때 적용.",
      docs: [{ label: "README (올리는 법·구조)", href: "/plandept/README.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "제작·배치. data.js 가 단일 출처" }, { d: "2026-09-04", t: "클코팀장 배포(rewrite 2줄·예약 슬러그 마이그레이션·push) → 두 주소 200 확인" }, { d: "2026-09-04", t: "클코팀장 지적(공개 경로) → 회장님 결정: 운영자 로그인으로 잠금 + 어드민 메뉴 버튼" }, { d: "2026-09-04", t: "잠금 배포(00acf40) — 두 대시보드 운영자 전용, 어드민 메뉴 '전략기획실'·'사업 설계서' 버튼. 참모 양방향 확인 완료" }],
    },

    /* ───────────── 기획완료 · 검토 대기 ───────────── */
    {
      id: "story-nudge", title: "스토리 넛지 — 카톡 한 통 · 20초 녹음 · 홈페이지가 자란다", stage: "planned", area: "제품", decision: "수락",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "회사마다 onstori.com/{slug}/story 페이지. 회장님 카톡으로 매주 화 12:00 '20초 녹음' 부탁 → 사장님이 카카오 로그인 뒤 녹음/글/사진 → AI가 말한 것만 정리(재수정 1회) → '이대로 올리기' → 게시. 운영자는 고객관리·검토함·설정·실험실 4화면.",
      why: "온스토리가 홈온과 다른 이유('스토리가 쌓이는 홈페이지')를 실제로 작동시키는 장치. 해지율을 정하는 기능. 비용은 고객당 월 10~200원.",
      status: "기획 확정(v3). 미정이던 6건 전부 결정 — 카톡 음성 두 뜻 모두 명시 · 이메일 로그인은 막지 않고 숨김 · 사진 8/20장 · 글 길이 보통(3~5문장) · 검토 알림은 회장님 문자+배지 · 검토함을 앞당겨 넛지와 같이 출시. 착수 대기.",
      next: "클코팀장 세션 N1(페이지·로그인 게이트) → N2(녹음·AI·게시) → N3(검토함·알림) → N4(프로덕션 확인). 운영자 나머지 3화면은 그 뒤. 시점: 스프린트 6(위젯) 뒤·7(R2-2) 앞.",
      docs: [{ label: "★★★ 최종 실행안 프로토타입 (카피 12안·영상 후처리·정책)", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }, { label: "★★ 이야기 엔진 프로토타입 v2 — 60초 영상·대본 엔진·원가표", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }, { label: "★ 이야기 엔진 프로토타입 (눌러보는 데모)", href: "/plandept/docs/story-engine-proto-2026-09-05.html", type: "html" }, 
        { label: "확정 결정표 & 실행 카드 (v3)", href: "/plandept/docs/story-nudge-decisions-2026-09-05.md", type: "md" },
        { label: "기획 v2 (카톡·카카오 로그인·AI 맥락·운영자 메뉴)", href: "/plandept/docs/story-nudge-plan-v2-2026-09-04.md", type: "md" },
        { label: "기획 v1 (사실 조사·사업성·문구 연구·자동화 로드맵)", href: "/plandept/docs/story-nudge-plan-v1-2026-09-04.md", type: "md" },
        { label: "샘플 페이지 v2 — onstori.com/abc/story", href: "/plandept/docs/story-page-sample-v2.html", type: "html" },
        { label: "운영 콘솔 시안 — 고객관리·검토함·설정·실험실", href: "/plandept/docs/story-console-sample.html", type: "html" },
        { label: "초안: 크론·알림톡 자동화판 (story-engine, 3단계 C용)", href: "/plandept/docs/story-engine-spec-draft-2026-09-04.md", type: "md" },
        { label: "옛 음성 데모 (ON secret)", href: "https://onsecret-onstori.vercel.app/1st_onstori/onstori-voice-demo.html", type: "link" },
      ],
      history: [
        { d: "2026-09-04", t: "회장님 원안(주간 넛지·음성·업종 라벨) → 참모 1차 평가(자동화판)" },
        { d: "2026-09-04", t: "회장님 수정안(카톡 예약·/story 페이지·원치않음) → v1: 사실 조사 3건(카톡 예약 반복 없음·채널 15원·안드로이드 인앱 녹음 불가)" },
        { d: "2026-09-04", t: "회장님 결정 9건 → v2: 카카오 로그인·AI 1회 재수정·사진 20장·운영자 4화면·자동 검토 규칙 8개" },
        { d: "2026-09-05", t: "남은 6건 확정 → v3 결정표. 실행 단위 N1~N4 로 재편(검토함 앞당김)" },
      ],
    },
    {
      id: "site-status", title: "고객 사이트가 아직 전부 '체험' 상태 — 검색엔진에 안 잡힘", stage: "planned", area: "영업·가격", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "sitemap.xml 에 onstori.com 루트 하나뿐이고 고객 사이트가 0건이다. 사이트맵은 status='active' 인 사이트만 싣고, /{slug} 페이지는 status='trial' 이면 noindex 를 붙인다. 실제로 goodmoksu 의 robots 메타가 'noindex, nofollow' 였다.",
      why: "경로 방식(onstori.com/{slug})을 택한 이유가 '도메인 1회 등록 + 통합 사이트맵으로 전 고객 SEO'였는데, 지금은 모든 고객이 trial 이라 그 이점이 하나도 실현되지 않고 있다. 스토리가 쌓여도 검색으로 들어오는 손님이 0이다.",
      status: "참모 발견(2026-09-05, 프로덕션 실측). 의도된 동작이긴 하다 — 체험 사이트를 색인시키지 않는 건 맞는 정책. 문제는 '언제 active 로 올리나'가 정해져 있지 않다는 것.",
      next: "회장님 결정: 무료 체험 고객도 발행하면 active 로 올릴지, 아니면 결제(P5) 시점에 올릴지. 전자면 오늘 바로 SEO 가 돌기 시작하고, 후자면 P5 까지 검색 유입 0 이 유지된다.",
      needs: ["체험 고객의 사이트를 색인 대상(active)으로 올릴 시점 — 발행 즉시 vs 결제 시점"],
      docs: [],
      history: [{ d: "2026-09-05", t: "미리보기 검증 중 sitemap.xml 이 루트 1건뿐인 것을 발견 → goodmoksu robots 메타 noindex 확인" }],
    },
    {
      id: "hero-picker", title: "히어로 사진 — 별점 선별 · 추천 3장 · 직접 등록(크롭)", stage: "planned", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "이미지뱅크에 ★1~5 채점(기존 quality_score에 매핑, 마이그레이션 없음) → 히어로는 ★4 이상만 뽑힘. 편집 화면 '사진 바꾸기'에 추천 3장 · AI 추천(태그 재선택, 0원) · 내 사진 크롭 업로드.",
      why: "원안의 절반(점수→우선 선택)은 이미 코드에 있고 638장이 전부 기본 50점일 뿐. 채점만 해도 새 사이트 품질이 즉시 오른다.",
      status: "제안서 있음. H1(별점)은 반나절·무위험, H2(편집 화면)는 미리보기(5) 뒤 1세션.",
      next: "회장님 결정 2건(히어로 비율 16:9 · 뱅크 내 교체 점수 0) → 수락 시 H1 먼저.",
      needs: ["히어로 표시 비율 기준(16:9 제안)", "뱅크 안에서 바꾸는 건 완성도 점수 0 유지(제안) vs 5점"],
      docs: [{ label: "기획서 (hero-image-picker.md)", href: "/plandept/docs/hero-image-picker-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "회장님 아이디어 → 참모 기획. ⚠ 실수로 저장소 docs/specs에 들어감 → 삭제 요청 중" }],
    },
    {
      id: "context-diet", title: "클로드코드 컨텍스트 다이어트 — STATUS.md ≤60줄, PROGRESS 아카이브", stage: "planned", area: "프로세스", decision: "수락",
      owner: "클코팀장", since: "2026-09-02", updated: "2026-09-03",
      summary: "PROGRESS.md(690줄)를 docs/archive로 옮기고 60줄짜리 STATUS.md를 만든다. ui.tsx(691줄)는 grep으로 필요한 부분만 읽고 새 탭은 별도 파일.",
      why: "클로드코드가 무거운 이유의 절반은 매 세션 끝난 일의 기록을 다 읽기 때문.",
      status: "스프린트 플랜 5장에 규칙으로 들어감. 정리 세션은 아직.",
      next: "한가한 세션에 정리 1회(Sonnet 5).",
      docs: [{ label: "스프린트 플랜 5장", href: "/plandept/docs/sprint-plan-2026-09-03.md", type: "md" }],
      history: [{ d: "2026-09-02", t: "에디터 v2 플랜에서 제안" }, { d: "2026-09-03", t: "스프린트 플랜에 규칙으로 채택" }],
    },
    {
      id: "wildcard", title: "*.onstori.com 옛 서브도메인 링크 살리기 (Cloudflare 리다이렉트)", stage: "planned", area: "인프라", decision: "대기",
      owner: "회장님(클릭 작업)", since: "2026-09-04", updated: "2026-09-04",
      summary: "Cloudflare 이전 후 와일드카드 레코드가 없어 goodmoksu.onstori.com 같은 옛 주소가 DNS에서 죽는다. Cloudflare에 '*' 레코드(프록시) + Redirect Rule 하나로 onstori.com/{서브도메인}으로 301. 코드 0.",
      why: "명함·카톡 프로필에 옛 주소가 뿌려져 있으면 지금 깨져 있다.",
      status: "클코팀장이 R2-1 작업 중 발견. 참모가 해법 제시. 뿌려진 옛 링크가 있는지부터 확인 필요.",
      next: "회장님 '해줘' 시 Cloudflare 클릭 순서 안내(10분).",
      docs: [],
      history: [{ d: "2026-09-04", t: "클코팀장 PROGRESS 병행·대기 항목 → 참모 해법" }],
    },

    /* ───────────── 기획중 ───────────── */
    {
      id: "preview", title: "에디터 라이브 미리보기 (postMessage + iframe)", stage: "done", area: "제품", decision: "확정",
      owner: "클코팀장", since: "2026-09-02", updated: "2026-09-05",
      summary: "저장하지 않아도 오른쪽/아래에 결과가 바로 보인다. lib/stories.ts 분리 → /[slug]/preview 페이지 → 에디터가 postMessage로 문서를 흘려보냄 → 자동저장.",
      why: "P5 진입 조건 2번. 홈온의 3단 캔버스 에디터 대비 가장 큰 체감 격차.",
      status: "적용완료 — 세션 A·B 모두 프로덕션 배포(c8dcbd2). 참모 프로덕션 검증: 세션 A 는 발행 사이트 5곳 배포 전/후 텍스트 완전 동일(바른전기 \"작업 기록 1건\" 불변), 세션 B 는 폰 폭에서 [미리보기] 시트 정상(iframe 11섹션 렌더·안내 띠 표시·body 스크롤 잠금·닫기 버튼). 클코팀장 실측 반영 178ms·팔레트 176ms·자동저장 DB 반영 확인. 미확인 1건: smooth 스크롤 애니메이션은 브라우저가 visibilityState=hidden 탭에서 실행하지 않아 자동화 환경에서 검증 불가(코드 경로·ready 시 doc+focusIndex 동시 전송은 확인됨) — 회장님 폰 30초 확인만 남음.",
      next: "회장님 폰에서 30초 확인(섹션 고치고 [미리보기] → 그 부분이 보이는지). 다음 순서는 플로팅 연결 위젯(6) — 참모가 스펙 작성 예정(스키마 변경이라 Opus·ultracode 필요).",
      docs: [
        { label: "실행 스펙 — 세션 A/B (2026-09-05)", href: "/plandept/docs/editor-preview-2026-09-05.md", type: "md" },
        { label: "에디터 v2 구축 플랜 (리포트)", href: "/plandept/docs/editor-v2-plan-2026-09-02.html", type: "html" },
      ],
      history: [{ d: "2026-09-02", t: "플랜 리포트" }, { d: "2026-09-03", t: "P5 조건으로 확정, 순서 5번" }, { d: "2026-09-05", t: "실행 스펙 작성 — 병목 한 줄 실측 확인, 세션 A/B 분리" }, { d: "2026-09-05", t: "회장님 승인(오른쪽 배치·자동저장 2초) → 세션 A 착수" }, { d: "2026-09-05", t: "세션 A 배포 완료 — 참모가 배포 전/후 5곳 대조, 변화 0 확인. /{slug}/preview 정상" }, { d: "2026-09-05", t: "세션 B 배포 완료(c8dcbd2). 참모가 프로덕션 폰 폭에서 시트·iframe·안내 띠·스크롤 잠금 확인" }],
    },
    {
      id: "widgets", title: "플로팅 전화·카톡 연결 위젯", stage: "planning", area: "제품", decision: "확정",
      owner: "클코팀장(Opus·ultracode)", since: "2026-09-02", updated: "2026-09-03",
      summary: "스크롤 어디서나 전화·카톡 버튼. SiteDoc.widgets[] 스키마 추가 — zod·렌더러·에디터 폼·SCHEMA.md 4곳을 한 커밋으로.",
      why: "P5 진입 조건 3번. 소상공인 홈페이지의 전환은 결국 전화 한 통.",
      status: "스프린트 6번. 이번 스프린트 유일한 스키마 변경 → Opus 5 + ultracode 예정.",
      next: "미리보기(5) 뒤. 세션 시작 전 참모가 Opus 필요 경고.",
      docs: [{ label: "에디터 v2 구축 플랜 (세션 D)", href: "/plandept/docs/editor-v2-plan-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-03", t: "P5 조건으로 확정" }],
    },
    {
      id: "editor-v2", title: "에디터 v2 — ui.tsx 분해·undo/redo·AI 다시쓰기·폰트/크기 테마", stage: "planning", area: "제품", decision: "보류",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-03",
      summary: "691줄 ui.tsx를 20파일로 분해, 되돌리기, AI 다시 쓰기, 폰트·크기 테마. 재작성 아님.",
      why: "홈온보다 빠르고 쉬운 에디터가 목표. 단 P5 조건 3개(미리보기·위젯·문의)와 분리해 뒤로.",
      status: "미리보기(5) 뒤 별도 세션으로 미룸(스프린트 플랜 3장).",
      next: "P5 3조건 끝난 뒤 재검토.",
      docs: [{ label: "에디터 v2 구축 플랜", href: "/plandept/docs/editor-v2-plan-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "플랜 리포트(당시엔 P4 직후 진행 권고)" }, { d: "2026-09-03", t: "P5 조건 3개만 앞으로, 나머지 보류" }],
    },
    {
      id: "story-pages-seo", title: "스토리 개별 페이지 SEO (/{slug}/story/{id})", stage: "planning", area: "제품", decision: "수락",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-04",
      summary: "스토리 한 편 = 검색 페이지 한 장. 홈온은 단일 페이지라 구조적으로 불가능한 롱테일 검색 유입.",
      why: "이기는 무기 2번. 스토리 넛지와 한 몸.",
      status: "스토리 넛지 v2 세션 1에 포함됨(/[slug]/story, /[slug]/story/[id], 사이트맵).",
      next: "스토리 넛지와 함께 진행.",
      docs: [{ label: "기술고문 리포트 (이기는 무기)", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "리포트 제안" }, { d: "2026-09-04", t: "스토리 넛지 v2에 합침" }],
    },

    /* ───────────── 준비중 ───────────── */
    {
      id: "alimtalk", title: "카카오 알림톡 채널 개통 (넛지·문의 알림 자동화)", stage: "prep", area: "운영", decision: "수락",
      owner: "회장님", since: "2026-09-03", updated: "2026-09-04",
      summary: "사업자등록 → 카카오 비즈니스 채널 → 정보성 템플릿 심사(1~2주) → lib/notify.ts에 채널 추가. 건당 약 8원.",
      why: "20곳 넘으면 회장님 손으로 카톡 예약을 못 건다. 자동화의 정도(正道).",
      status: "사업자등록(P5 전제)과 함께 신청 권고. 코드는 notify.ts 한 곳.",
      next: "사업자등록 시점에 채널·템플릿 신청.",
      docs: [{ label: "기획 v1 5장 알림 채널 비교", href: "/plandept/docs/story-nudge-plan-v1-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-03", t: "문의 알림 스펙에 'P5 이후 채널 추가'로 예약" }, { d: "2026-09-04", t: "넛지 B단계 채널로 확정" }],
    },
    {
      id: "backup", title: "DB 백업 공백 해결 (pg_dump — GitHub Actions 또는 Supabase Pro)", stage: "prep", area: "인프라", decision: "수락",
      owner: "클코팀장", since: "2026-09-03", updated: "2026-09-03",
      summary: "작업 PC에 Docker·pg_dump가 없어 supabase db dump가 안 됨. backups/ 가 P1 이후 비어 있음.",
      why: "실고객 데이터가 쌓이기 시작했다. 결제 전 반드시.",
      status: "P5 전 검토 항목. 방안 2개(GitHub Actions 주 1회 pg_dump / Supabase Pro 자동 백업).",
      next: "P5 전 세션 1회.",
      docs: [{ label: "스프린트 플랜 4장", href: "/plandept/docs/sprint-plan-2026-09-03.md", type: "md" }],
      history: [{ d: "2026-09-03", t: "클코팀장 아침 점검에서 실패 확인" }],
    },
    {
      id: "fabrication-filter", title: "AI 카피 날조 후처리 필터", stage: "prep", area: "법무·정책", decision: "수락",
      owner: "클코팀장", since: "2026-09-02", updated: "2026-09-03",
      summary: "프롬프트만으로 '오랜 노하우' 같은 근거 없는 경력 표현을 100% 못 막는다. 게시 전 정규식+AI 2차 검수 필터.",
      why: "표시광고법(CLAUDE.md 불변규칙 7). 실사이트 3곳에서 이미 발견됨.",
      status: "프롬프트 규칙 확대·copyModel 기록은 적용 완료. 후처리 필터는 미착수. 스토리 넛지 v2의 '2차 검수'와 같은 부품.",
      next: "스토리 넛지 세션 2에서 공용 모듈로 만들면 사이트 생성에도 재사용.",
      docs: [{ label: "기술고문 리포트 (부족한 지점 12)", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-03", t: "발행 사이트 3곳 문구 제거 + 프롬프트 확대(부분 적용)" }],
    },
    {
      id: "industry-scope", title: "범위 밖 업종 처리 — 범용 업종 2종 + 저확신 되묻기", stage: "prep", area: "제품", decision: "대기",
      owner: "회장님 결정", since: "2026-09-02", updated: "2026-09-03",
      summary: "v1은 시공 12업종 + 카페·식당. 필라테스·미용실 같은 업종이 들어오면 지금은 어색한 사이트가 나온다. 권고: 범용 업종 2종(서비스형/매장형) + 확신 낮으면 1회 되묻기.",
      why: "당근 홍보를 시작하면 불특정 업종이 바로 들어온다.",
      status: "사장님 결정 대기(P2 잔여).",
      next: "결정 → 클코팀장 1세션.",
      docs: [{ label: "기술고문 리포트", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "리포트 권고" }],
    },

    /* ───────────── 아이디어 ───────────── */
    {
      id: "pricing", title: "가격 개편 — 제작비 0원 · 단일 플랜 월 12,900 / 연 99,000", stage: "idea", area: "영업·가격", decision: "대기",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-02",
      summary: "홈온(제작 49,000 + LIGHT 9,900 / BUSINESS 39,900)에 맞선 제안: 제작비 0원, 단일 플랜에 문의함·위젯·표기 숨김을 기본 포함. 유료 게이트는 도메인 연결·표기 숨김만.",
      why: "홈온이 BUSINESS(39,900)에 가둔 '돈 내는 이유' 기능을 기본으로 풀면 비교표에서 이긴다. 회장님이 언급한 월 49,000원안과 함께 검토 필요.",
      status: "리포트 제안. 회장님 승인 대기. P5(결제) 설계의 입력값.",
      next: "P5 착수 전 결정.",
      docs: [{ label: "기술고문 리포트 (가격)", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "리포트 제안" }],
    },
    {
      id: "share-sheet", title: "PWA 공유 시트 + Gemini Vision 사진 캡션", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-02",
      summary: "폰 사진 앱에서 '공유 → 온스토리'로 바로 스토리 올리기. AI가 사진을 보고 캡션 초안.",
      why: "이기는 무기 3번. 스토리 넛지가 자리 잡은 뒤 다음 단계.",
      status: "아이디어. 스토리 넛지 결과 보고.",
      next: "넛지 4주 실험 후.",
      docs: [{ label: "기술고문 리포트", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "리포트 제안" }],
    },
    {
      id: "review-link", title: "후기 요청 링크 (별점 없이, 실후기만)", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-02",
      summary: "공사 끝난 손님에게 보내는 후기 링크. 별점 없음(표시광고법·컨셉 일치), 사진+한 줄.",
      why: "홈온은 협찬 후기 의존. 실후기가 쌓이면 신뢰 격차.",
      status: "아이디어(P8).",
      next: "P8.",
      docs: [{ label: "기술고문 리포트", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "리포트 제안" }],
    },
    {
      id: "refund-export", title: "환불 · 내 데이터 내보내기 정책", stage: "idea", area: "법무·정책", decision: "대기",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-02",
      summary: "홈온엔 환불 조항이 없다. '언제든 해지·내 사진과 글은 zip으로 가져가기'를 약속하면 가입 장벽이 낮아진다.",
      why: "약점 공략 + 신뢰.",
      status: "아이디어(P9 법무).",
      next: "P9.",
      docs: [{ label: "기술고문 리포트", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "리포트 제안" }],
    },
    {
      id: "stats", title: "사장님 통계 — 방문·전화 클릭·유입 + 월간 리포트 문자", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-04",
      summary: "events 테이블(visit·call_click·story_view)은 이미 있음. 대시보드 + 월 1회 '이번 달 방문 N명·전화 M건' 문자.",
      why: "넛지 문구에 '지난주 방문 23명'이 들어가는 순간 응답률이 뛴다. 해지 방어의 근거 숫자.",
      status: "P7. 스토리 넛지 다음 단계.",
      next: "P7.",
      docs: [{ label: "기술고문 리포트 (리드 엔진)", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "리포트 제안" }, { d: "2026-09-04", t: "넛지 v1에서 '받는 이득이 있는 메시지'로 재언급" }],
    },
    {
      id: "custom-domain", title: "고객 커스텀 도메인 연결 (companyname.com)", stage: "idea", area: "인프라", decision: "대기",
      owner: "기술참모", since: "2026-09-03", updated: "2026-09-03",
      summary: "Vercel Domains API로 고객 도메인 추가 → 등록기관 레코드 안내 → 검증 → Host 헤더로 사이트 조회. 수동/반자동 먼저, 가비아 리셀러 자동 구매는 나중.",
      why: "유료 게이트 후보. 홈온은 이 기능이 불안정.",
      status: "P5 이후. custom-domain.md 분리 예정.",
      next: "P5 이후.",
      docs: [{ label: "R2 스펙 2-2절", href: "/plandept/docs/storage-r2-spec-2026-09-03.md", type: "md" }],
      history: [{ d: "2026-09-03", t: "R2 논의 중 원리 정리" }],
    },
    {
      id: "kenburns", title: "히어로 무비 대체 — 사진 3~5장 Ken Burns 슬라이드", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-03",
      summary: "199,000원 맞춤 무비(P6)를 런칭 범위에서 빼고, 사진이 천천히 움직이는 슬라이드로 '살아있는 첫 화면'을 0원에.",
      why: "무비는 수정 3회·검수·표시광고법 리스크가 크고 판매 전 검증이 안 됐다.",
      status: "사장님 결정 대기(무비 제외 승인).",
      next: "결정.",
      docs: [{ label: "기술고문 리포트", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "리포트 권고" }, { d: "2026-09-03", t: "스프린트 플랜 '뒤로 미룬 것'에 기록" }],
    },
    {
      id: "brandkit", title: "브랜드키트 (로고 3안·명함·QR·도장) — 규칙 기반", stage: "idea", area: "제품", decision: "보류",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-03",
      summary: "홈온의 브랜드키트에 대응. 워드마크 SVG 조판 + 템플릿 규칙으로 AI 생성 없이.",
      why: "P6. 문의·스토리보다 뒤.",
      status: "보류(P6).",
      next: "P6.",
      docs: [],
      history: [{ d: "2026-09-03", t: "P5 이후로" }],
    },


    /* ───────────── 새 아이디어 (2026-09-04 저녁, 참모 구상) ───────────── */
    {
      id: "before-after", title: "시공 전·후 비교 슬라이더 섹션 (Before/After)", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "시공·청소·도배 업종에서 가장 설득력 있는 한 장면은 '전과 후'다. 사진 두 장을 올리면 손가락으로 밀어 비교하는 섹션. 스토리 넛지에서 '전 사진·후 사진' 두 칸을 받으면 자동으로 이 형식이 된다.",
      why: "사실 사진은 표시광고법 문제가 없다(의료만 심의 대상). 홈온엔 없는 섹션. 견적 문의 전환에 직접 효과.",
      status: "아이디어. 섹션 스키마 추가(zod·렌더러·에디터 폼·SCHEMA.md 한 커밋)라 위젯(6)과 같은 세션에 묶으면 스키마 변경을 한 번으로 끝낼 수 있다.",
      next: "회장님 판단 → 위젯 세션에 동승 여부.",
      docs: [], history: [{ d: "2026-09-04", t: "참모 구상" }],
    },
    {
      id: "quote-calc", title: "간이 견적 계산기 (평수·항목 → 예상 범위 → 문의 전환)", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "사장님이 단가표(예: 도배 평당 ○○원, 최소 ○○원)를 한 번 넣으면, 손님이 평수·항목을 고르고 '예상 범위'를 본 뒤 그 값이 붙은 채로 견적 문의가 접수된다. 옛 계획 v3에도 있던 항목.",
      why: "'대충 얼마예요?'가 소상공인 첫 통화의 절반이다. 범위를 먼저 보여주면 허수 문의가 줄고 진성 문의가 남는다. 문의 접수(inquiry) 위에 얹는 기능.",
      status: "아이디어. 표시광고법: '예상 범위, 현장 확인 후 확정' 문구 필수. 견적 접수 G2 이후.",
      next: "P5 3조건 뒤 검토. 스펙 1장짜리.",
      docs: [], history: [{ d: "2026-09-04", t: "참모 구상(옛 계획 v3 계승)" }],
    },
    {
      id: "story-repost", title: "스토리 → 인스타·블로그·당근 복붙 문구 자동 생성", stage: "dropped", area: "제품", decision: "폐기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "스토리를 올리면 같은 내용으로 인스타 캡션·네이버 블로그 초안·당근 소식 문구를 만들어 '복사' 버튼으로 준다는 안. → 'autopost'(음성 한 번 → 4곳 동시 게시) 항목으로 확장 흡수됨. 폐기가 아니라 승격.",
      why: "복붙만으로는 사장님 손이 여전히 간다. 인스타·쓰레드는 API로 실제 발행이 가능하다는 조사 결과(2026-09-04)가 나와 자동 발행까지 올림.",
      status: "autopost 로 통합.",
      next: "autopost 항목 참조.",
      docs: [{ label: "해외 AI 홈페이지 벤치마크 & 차별화 전략", href: "/plandept/docs/global-ai-builder-benchmark-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "참모 구상" }, { d: "2026-09-04", t: "벤치마크 조사 후 autopost 로 승격·통합" }],
    },
    {
      id: "link-kit", title: "주소 뿌리기 키트 — 명함 QR · 카톡 프로필 링크 · 플레이스 안내 카드", stage: "idea", area: "영업·가격", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "발행 직후 '홈페이지 주소를 3곳에 거세요' 카드: ①카톡 프로필 링크 넣는 법 ②네이버 플레이스 홈페이지 칸 ③명함용 QR(png 다운로드). 각 항목에 완성도 점수.",
      why: "홈페이지는 뿌려야 방문이 생기고, 방문이 있어야 문의가 온다. 지금은 발행하고 끝. 비용 0, 하루짜리.",
      status: "아이디어. QR은 라이브러리 하나(qrcode). 완성도 규칙표(completeness.ts)에 항목 3개 추가.",
      next: "미리보기(5) 전후 자투리 세션.",
      docs: [], history: [{ d: "2026-09-04", t: "참모 구상" }],
    },
    {
      id: "referral", title: "사장님 소개 프로그램 — 소개하면 양쪽 1개월 무료", stage: "idea", area: "영업·가격", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "소상공인은 같은 업종 사장님 카톡방이 있다. 마이페이지에 '소개 링크' 하나, 소개받은 사장님이 유료 전환하면 둘 다 1개월 무료.",
      why: "당근·콜드콜보다 싼 획득 채널. 결제(P5)가 있어야 '무료 1개월'을 줄 수 있으므로 P5 직후.",
      status: "아이디어. sites.referred_by 한 열 + 마이페이지 링크 + 결제 크레딧.",
      next: "P5 설계에 포함 여부 결정.",
      docs: [], history: [{ d: "2026-09-04", t: "참모 구상" }],
    },
    {
      id: "demo-kit", title: "시연 키트 — 5분 시나리오 + 데모 사이트 + 회장님 폰 체크리스트", stage: "idea", area: "프로세스", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "P5 진입 조건의 마지막은 '실제 사장님에게 시연'. 즉흥이 아니라 5분 대본(문의 접수 → 문자 도착 → 미리보기에서 사진 바꾸기 → 카톡 20초 넛지)과 시연용 데모 사이트, 실패 시 대안 경로를 미리 만든다.",
      why: "시연 3번이면 P5 착수. 대본이 있어야 사장님 반응을 같은 잣대로 비교할 수 있다.",
      status: "아이디어. 코드 없음. 참모가 대본 작성 → 회장님 리허설.",
      next: "위젯(6) 끝나면 작성.",
      docs: [], history: [{ d: "2026-09-04", t: "참모 구상" }],
    },

    /* ───────────── 새 아이디어 (2026-09-04 해외 벤치마크 결과, 참모 구상) ───────────── */
    {
      id: "autopost", title: "★ 음성 한 번 → 홈페이지 + 인스타 + 쓰레드 동시 게시 (원소스 멀티포스트)", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "확정된 스토리 넛지(화요일 12시 카톡 → 사장님 음성 30초 + 사진)에 한 단계만 더 붙인다. AI가 ①홈페이지 스토리 글 ②인스타 캡션+해시태그(사진 정사각 크롭) ③쓰레드 글 ④네이버 블로그 초안 을 동시에 만들고, 카톡으로 '이렇게 나갑니다 [게시]' 확인을 받은 뒤 홈페이지·인스타·쓰레드에 실제로 발행한다. 네이버·당근은 API가 없어 복사 버튼 + 앱 열기 링크(반자동).",
      why: "해외 20개 서비스 조사 결과 '카톡 음성 한 번 → 홈페이지+SNS 동시 게시'를 하는 곳이 0곳이다. Wix·GoDaddy는 SNS 발행은 되지만 음성 입력이 없고 홈페이지 글과 SNS 글이 따로 논다. Durable·BASE·凡科는 글만 만들고 발행은 수동. 아임웹·카페24·홈온은 SNS 자동 게시 자체가 없다. 50~60대 사장님은 블로그는 안 써도 카톡 음성은 매일 쓴다. 한 문장으로 팔린다 — '말만 하세요. 홈페이지도 인스타도 알아서 올라갑니다.'",
      status: "기술 타당성 **검증 완료**(2026-09-04 밤, Meta 공식문서 직접 확인). 발행 API 완전 무료 — 호출당 과금·구독료·유료 티어 없음, Meta가 돈 받는 건 WhatsApp 하나뿐. 2026-04 Meta 는 오히려 서드파티 관리 API 를 무상 확대. 한도는 앱 전체가 아니라 계정마다 따로 계산돼 고객이 늘면 한도도 늘어남(스케일 병목 없음). 이미지는 **JPEG 만, 8MB, 4:5~1.91:1**(기본값 1080×1350 고정) — 여기서 제일 많이 깨짐. 스토리·릴스도 발행 가능. ⚠ 실제 비용은 돈이 아니라 **연 1회 DPA 를 60일 안에 못 끝내면 전 고객 발행이 한꺼번에 멈춤**. 유사 서비스 조사: 통째로 하는 곳 없음 — Blaze(자동발행·음성X), Clipsy(음성·발행X), Blog2Social(홈페이지→인스타·쓰레드 자동, 5만 설치·4.5점), Mirra(한국·쓰레드 지원·승인 후 발행), 가제트(네이버 자동포스팅 월 19,800원).",
      next: "회장님 결정 2건 — ①1순위 확정 ②Meta 앱 심사 지금 신청. 확정 시 세션 5개(다중 출력 생성 / 계정 연결·온보딩 위저드 / 발행 API / 승인 게이트 / **중복 방지 dup-guard**).",
      needs: ["스토리 넛지 N1~N4 선행", "Meta 앱 심사 통과(6~8주)", "인스타는 프로페셔널 계정만 가능(계정 자동 생성은 약관 위반·불가 → 3분 온보딩 위저드로 대체)", "dup-guard(중복 방지) 동반 필수"],
      docs: [{ label: "★★ 이야기 엔진 프로토타입 v2 — 60초 영상·대본 엔진·원가표", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }, { label: "★ 실행 타당성 검증 (회장님 질문 9건 답)", href: "/plandept/docs/autopost-feasibility-2026-09-04.md", type: "md" }, { label: "해외 AI 홈페이지 벤치마크 & 차별화 전략", href: "/plandept/docs/global-ai-builder-benchmark-2026-09-04.md", type: "md" }, { label: "스토리 넛지 결정 v3", href: "/plandept/docs/story-nudge-decisions-2026-09-05.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "회장님 '혁신 기능 최소 1개' 요청 → 해외 20개 벤치마크 → 1순위로 제안" }],
      side: "토큰비 확인: Gemini 2.5 Flash 기준 4종 동시 생성 약 5원, 음성·이미지·재수정 포함해도 건당 30~50원. 고객 100명 월 2만 원 = 매출의 0.4%. 'AI 크레딧 없음'을 약속해도 원가가 안 된다.",
    },
    {
      id: "meta-review", title: "Meta 앱 심사 신청 (인스타·쓰레드·페북 발행 권한) — 6~8주 대기", stage: "planned", area: "프로세스", decision: "대기",
      owner: "회장님(서류) · 클코팀장(앱 등록)", since: "2026-09-04", updated: "2026-09-04",
      summary: "고객 계정에 대신 게시하려면 Meta 앱 심사(App Review) + 사업자 인증이 필요하다. 필요 서류는 사업자등록증·개인정보처리방침·기능 시연 영상. 인스타·쓰레드·페이스북 권한을 한 앱에서 한 번에 신청한다.",
      why: "심사가 20일~6주(실무 6~8주)라 지금 신청하지 않으면 위젯·시연이 끝나고도 autopost 를 못 켠다. 오늘 신청하면 10월 말~11월 초 개통. 이것 하나만 늦어도 1순위 기능 전체가 밀린다.",
      status: "미신청. Business 타입 앱 + App Review + Advanced Access + 비즈니스 인증이 한 묶음. ⚠ **통과 후에도 연 1회 DPA(개인정보 보호 평가)와 Data Use Checkup 이 오고, DPA 는 통보 후 60일 안에 완료하지 않으면(답이 모호해도) 플랫폼 접근을 잃는다** — 그 순간 전 고객의 SNS 자동 게시가 한꺼번에 멈춘다. 알림은 앱 관리자 이메일로만 오므로 캘린더 등록 필수. 대안으로 Ayrshare(Launch $299/월·프로필 10개)를 시연용으로 먼저 쓰는 길도 있으나 고객 100명이면 월 170만 원.",
      next: "회장님 승인 → 클코팀장이 Meta 개발자 앱 생성 → 서류 제출.",
      needs: ["사업자등록증", "개인정보처리방침 URL", "기능 시연 영상"],
      docs: [{ label: "해외 AI 홈페이지 벤치마크 & 차별화 전략 (4장)", href: "/plandept/docs/global-ai-builder-benchmark-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "SNS 발행 타당성 조사 중 병목으로 확인 — 최우선 착수 항목으로 분리" }],
    },
    {
      id: "geo-aio", title: "AI 검색 노출 (ChatGPT·제미나이가 우리 손님 가게를 추천하게)", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "사이트마다 llms.txt 자동 생성, 구조화 데이터(JSON-LD: LocalBusiness·영업시간·지역·서비스) 자동 삽입, 스토리에서 자주 나오는 질문을 뽑아 FAQ 자동 생성, 대시보드에 'AI 검색 노출 점수' 표시.",
      why: "Squarespace(AIO Scanner)·Durable(SEO+GEO)·凡科(GEO 서비스)가 이미 유료 상품으로 판다. 국내엔 아직 아무도 없다. 네이버 노출은 우리가 통제 못 하지만 이건 통제 가능하다. '네이버에만 나오는 홈페이지는 반쪽입니다' 라는 세일즈 문구가 나온다. 구현 반나절~하루.",
      status: "아이디어. 검색 노출 정책(체험 중 noindex) 논의와 직접 연결됨.",
      next: "회장님 결정 — 위젯 앞에 반나절 넣을지.",
      docs: [{ label: "해외 AI 홈페이지 벤치마크 (2장 ②·⑩, 6-2장)", href: "/plandept/docs/global-ai-builder-benchmark-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "벤치마크에서 발견 — 2순위로 제안" }],
    },
    {
      id: "health-score", title: "사이트 완성도 점수 · 자동 건강검진", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "편집기 상단에 '이 사이트 완성도 62점' + 체크리스트(사진 없는 섹션 3개 / 빈 문구 2곳 / 전화번호 미입력 / 깨진 링크). 채울 때마다 점수가 오르고, 90점을 넘으면 '검색 노출 켜기' 버튼이 열린다.",
      why: "참모가 실제 5개 사이트를 확인한 결과 문제는 디자인보다 빈칸이었다('안내 문구를 입력해 주세요' 노출, 가격이 500000 그대로, 테스트 문구 방치). Framer 가 같은 기능(자동 감사)을 에이전트로 판다. 완성도 게이트 논의도 이 하나로 해결되고, AI 가 잔소리가 아니라 도움으로 느껴진다.",
      status: "아이디어. 'site-status'(사이트 상태·삭제 카운트다운)와 짝. 빈 섹션 숨기기·숫자 포맷 수정과 같은 세션으로 묶으면 반나절~하루.",
      next: "회장님 결정 — 위젯 앞에 넣을지.",
      docs: [{ label: "해외 AI 홈페이지 벤치마크 (6-3장)", href: "/plandept/docs/global-ai-builder-benchmark-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "벤치마크 + 실사이트 점검 결과 결합 — 3순위로 제안" }],
    },
    {
      id: "naver-reply", title: "네이버 리뷰 답변 초안 자동 생성 (승인식)", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "손님 리뷰가 달리면 AI가 답변 초안을 만들어 사장님에게 보내고, 사장님이 승인하면 복사해서 붙여넣는다. Durable 의 '구글 리뷰 답변 에이전트(승인 대기)'를 네이버판으로.",
      why: "리뷰 답변은 사장님이 제일 미루는 일이고, 플레이스 노출에도 영향이 있다. AI 호출 1회(1원). 다만 네이버 리뷰를 가져올 공식 경로가 없어 붙여넣기 입력이 전제 — 타당성 재확인 필요.",
      status: "아이디어. 별점 표시는 표시광고법 이슈로 금지(CLAUDE.md), 답변 초안은 별개.",
      next: "autopost 이후 검토.",
      docs: [{ label: "해외 AI 홈페이지 벤치마크 (2장 ⑤)", href: "/plandept/docs/global-ai-builder-benchmark-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "Durable 벤치마크에서 착안" }],
    },
    {
      id: "site-import", title: "기존 사이트 주소만 넣으면 온스토리로 이전", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "아임웹·카페24·홈온·네이버 모두홈 등에서 쓰던 사이트 URL 하나를 넣으면 AI가 내용을 읽어 온스토리 섹션으로 재구성한다. 10Web(Clone/Redesign)·알리바바 万小智(一键复刻)·ペライチ(특허 출원)가 모두 갖춘 기능.",
      why: "'0에서 만들기'보다 '지금 쓰는 것 옮기기'가 전환이 훨씬 쉽다. 경쟁사 고객을 그대로 데려온다.",
      status: "아이디어. 난이도 중~상(크롤링·이미지 반입·저작권 확인 필요). 남의 사이트를 그대로 복제하지 않도록 '본인 사이트 확인' 절차 필요.",
      next: "autopost·위젯 이후.",
      docs: [{ label: "해외 AI 홈페이지 벤치마크 (2장 ⑦·⑨)", href: "/plandept/docs/global-ai-builder-benchmark-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "10Web·알리바바 벤치마크에서 착안" }],
    },
    {
      id: "no-credit", title: "'AI 크레딧 없음' 을 가격 정책 차별점으로", stage: "idea", area: "영업·가격", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "Wix·Framer·Hostinger·10Web·B12 는 전부 AI 크레딧제이고, 2026년 리뷰의 신규 불만 1위가 '크레딧이 어디로 갔는지 모르겠다'이다. 온스토리는 '크레딧 없음, 몇 번을 고치셔도 49,000원'으로 간다. 안전장치로 고객당 월 상한(예: 200회)만 조용히 건다.",
      why: "원가 구조상 실제로 가능한 약속이다. Gemini 2.5 Flash 기준 고객 100명 월 토큰비 약 2만 원 = 매출 490만 원의 0.4%. 그리고 국내 경쟁(인마케팅 광고주센터)은 홈페이지 없이 AI 콘텐츠 생성만으로 월 49,000원을 받는다 — '콘텐츠만 만들어주는 곳도 49,000원입니다. 온스토리는 홈페이지까지 드리고 SNS에 대신 올려드리고 49,000원입니다.'",
      status: "아이디어. 가격 확정('pricing') 논의에 반영할 근거.",
      next: "시연 때 이 문구로 반응 확인.",
      docs: [{ label: "해외 AI 홈페이지 벤치마크 (7·8장)", href: "/plandept/docs/global-ai-builder-benchmark-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "벤치마크 가격 비교표에서 도출" }],
    },

    {
      id: "dup-guard", title: "★ 중복 방지 장치 — 계정 정지·저품질을 막는 안전장치", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "① 인사말·맺음말 같은 상용구 템플릿을 아예 만들지 않는다 ② 발행 전 문장 단위(n-gram) 중복 검사 — 다른 고객 글과 겹치면 재생성 ③ 계정 간 발행 시각을 흩뿌린다(지터), 정각 동시 발행 금지 ④ 계정별 일일 상한을 Meta 한도(인스타 100·쓰레드 250)보다 훨씬 낮게 자체 설정.",
      why: "autopost 의 최대 리스크는 기술이 아니라 **같은 문장이 여러 사장님 계정에 퍼지는 것**이다. Meta 개발자 정책은 \'높은 빈도의 봇 동작\'을 명시 금지하고 위반 앱은 기능 제한→일시중지→플랫폼 제거까지 간다. 네이버는 같은 문장이 여러 블로그에 퍼지면 원본 1개만 남기고 전부 복사글 처리한다. 양쪽에서 동시에 걸린다. 국내 경쟁사(블로그 팩토리·Mublo·에이블로)는 아무도 이걸 보증하지 않는다 → \'저품질 안 나게 설계된 유일한 서비스\'가 우리 포지션이 된다.",
      status: "기획 중. autopost 와 반드시 같이 나가야 함(따로 내면 의미 없음).",
      next: "autopost 확정 시 같은 세션 묶음에 포함.",
      docs: [{ label: "실행 타당성 검증 (3장·5장)", href: "/plandept/docs/autopost-feasibility-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "Meta 정책·네이버 유사문서 조사 중 최대 리스크로 확인 — 별도 항목으로 분리" }],
    },
    {
      id: "nudge-schedule", title: "넛지 주기·요일 사장님 설정 + 체험 중 매일 알림", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "설정 화면에 요일·시각·빈도(주1회·주2회·매일)·\'이번 주 건너뛰기\'·3회 무응답 시 자동 완화. **체험 기간에는 매일 알림이 기본값**, 결제 후 사장님이 낮춘다. 홈페이지 스토리는 발행 무제한.",
      why: "회장님 안 — \'2주간 매일 글이 쌓이면 버리기 어려워 결제한다\'. 그런데 주 1회 넛지로는 2주에 2개밖에 안 쌓인다. 매일 쓰게 하려면 매일 물어야 한다. 무료체험 유료 전환율 벤치마크는 양호 8~12%·우수 15~25%(프리미엄 방식은 3~8%) — 체험 방식이 2~3배 유리하다.",
      status: "기획 중. **발송 수단이 핵심 제약** — 카톡 개인 1:1 예약은 반복이 안 돼(월 4개 수동) 요일 자유 설정·매일 발송이 불가능. 문자(솔라피)는 이미 라이브(G2 에서 sms:true 확인)라 지금 당장 자동화 가능. 순서: ①문자 자동(요일·시각·빈도 UI) → ②사업자등록 후 알림톡 이관(4.8원/건, 카톡으로 도착) → ③카톡 개인 발송은 초기 5~10명 수작업만.",
      next: "회장님 결정 — 체험 중 매일 알림을 기본값으로 할지, 발송 수단을 문자로 확정할지.",
      needs: ["체험 기간 7일 vs 14일 결정(2주 락인 전략과 정합하려면 14일)"],
      docs: [{ label: "실행 타당성 검증 (4장·7장)", href: "/plandept/docs/autopost-feasibility-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "회장님 \'요일 설정·매일 알림·대시보드 거절\' 요청 → 발송 수단 제약 확인 후 설계" }],
    },
    {
      id: "naver-copy", title: "네이버 블로그 복붙 메뉴 (글 복사·사진 복사 + 30초 안내)", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "어드민/에디터에 \'네이버 블로그에 올리기\' 메뉴 — 글 복사 버튼, 사진 복사 버튼, 그대로 따라 하는 3단계 안내, 블로그 앱 바로 열기. **사진 3장 이상 없으면 복사 버튼 비활성화, 하루 1개 상한, 온보딩 고지문.**",
      why: "네이버는 API 가 없어(블로그 글쓰기 API 2020년 폐지) 자동 발행이 불가능하다. 반자동이 유일한 길. 저품질 리스크는 **AI 가 썼다는 사실이 아니라** 중복·대량·짧은 글·사진 없음에 있다 — 네이버 공식: \'좋은 문서라면 문서 생성 방식과 관계없이 검색에 노출이 가능합니다\'. 네이버 자신이 2023년 블로그용 AI 작문 도구(클로바 for Writing)를 창작자에게 공급했다.",
      status: "기획 중. 설계 원칙 = **완성 원고가 아니라 빈칸 있는 뼈대** — AI 는 제목 후보·소제목·FAQ 틀만 만들고 본문 핵심은 사장님 음성 내용으로만 채운다(네이버가 요구하는 \'솔직한 경험\'·\'독창성\' 충족 + 고객 간 중복 원천 차단). ⚠ EXIF 어쩌고는 근거가 없으니 마케팅 문구로 쓰지 말 것. 2026 변화: AI 브리핑이 검색 쿼리 약 20% 처리, 네이버 메이트가 \'AI 브리핑 인용 횟수\'로 월 30만~1,000만 원 지급(연 200억) → 블로그 평가 기준이 \'순위\'에서 \'AI 인용 가치\'로 이동 → FAQ·비교표·수치 구조로 써야 함(geo-aio 와 같은 방향).",
      next: "autopost 뒤. 지역 업종은 스마트플레이스(리뷰·행동 신호)를 1순위로 안내하는 편이 낫다는 점도 함께 검토.",
      docs: [{ label: "실행 타당성 검증 (5장)", href: "/plandept/docs/autopost-feasibility-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "회장님 \'복붙 메뉴 만들어도 됨? 저품질 안 먹어?\' → 네이버 정책·알고리즘 조사 후 설계" }],
    },
    {
      id: "trial-bar", title: "체험 바 — 사장님 화면은 크게, 손님 화면은 작은 배지", stage: "planning", area: "영업·가격", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "사장님 편집·미리보기 화면에는 카운트다운 + [지금 활성화] + 오늘의 혜택을 크게. 손님이 보는 발행 사이트에는 \'온스토리로 만든 홈페이지\' 작은 배지 하나만.",
      why: "⚠ 회장님 안(\'손님 화면에도 큰 바를 띄워 사실상 기능 테스트만 하게 한다\')은 **락인을 스스로 깬다**. 락인은 \'내 사이트를 손님에게 보여줬고 문의가 왔다\'는 경험에서 나오는데, 손님 화면을 광고로 도배하면 사장님이 주소를 아무에게도 안 뿌리고 → 문의 0건 → 결제할 이유가 사라진다. P5 진입 조건이 \'문의가 실제로 왔다\'인 것과 정면 충돌. 압박은 사장님에게만 유효하다.",
      status: "기획 중. 업계 관행 확인 — Wix 상단 배너+푸터 문구, Jimdo 푸터 광고+jimdofree 도메인, Webador 하단 광고(**사이트 색상에 맞춰 자동 변색** — 가장 영리함), 아임웹 하단 배너, Squarespace 만 **강제를 버리고 자발적 옵션**으로 전환. 효과 근거는 약함 — 통제된 A/B 데이터 공개 없음, Mailchimp 사례(2009 배지+추천보상 → 1년 만에 사용자 8.5만→45만, 유료 +150%)가 유일한 인용거리이나 배지만의 기여는 분리 불가.",
      next: "회장님 결정 — 손님 화면을 깨끗하게 둘지. 배지를 압박 장치가 아니라 유입 채널(배지 클릭 → 온스토리 가입)로 설계하고 시연 때 A/B 확인 권고.",
      docs: [{ label: "실행 타당성 검증 (8장)", href: "/plandept/docs/autopost-feasibility-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "회장님 홈온 체험 바 캡처 제시 → 업계 관행 조사 후 사장님/손님 화면 분리 권고" }],
      side: "site-status(체험 종료·삭제 카운트다운)와 짝. 삭제 전 \'내 글 전부 내려받기\' 버튼은 반드시 필요 — 없으면 나쁜 후기가 남고, 있어도 대부분은 안 누르고 결제한다.",
    },

    {
      id: "site-brain", title: "★ 3분 AI 인터뷰 → 가게 두뇌(사이트 프로필)", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "가입 때 필수 4개(상호·전화·slug·주소)는 지금처럼 폼으로 받고, 그 뒤에 **6문항을 한 번에 하나씩 대화로** 묻는다(말로 답해도 됨). ①무슨 일 ②어떤 손님 ③다른 곳과 뭐가 다른지 ④손님이 자주 묻는 것 3개 ⑤**안 하는 일** ⑥시작한 계기. AI 는 답이 짧을 때만 2번까지 되묻는다. 마지막에 **\'가게 카드\' 확인 화면**(이렇게 이해했습니다 → 고칠 곳 탭)을 보여준 뒤 생성. 답변과 함께 **사장님 말투**(어미·자주 쓰는 말·문장 길이·원문 샘플)를 저장한다.",
      why: "⚠ **지금 온스토리는 가게에 대해 두 문장만 알고 그마저 버린다**(저장소 확인: /new 는 필수 4개 폼, generate.ts 는 \'하는 일 한 줄\'로 분류+카피 1회, 프로필은 어디에도 안 남음). 그래서 나중에 스토리·인스타 캡션·블로그 초안·위젯 문구를 만들 때 AI 가 매번 백지에서 시작한다 — 이게 \'AI 티 난다\'의 진짜 원인. 대화형 근거: 폼 완료율 21.5% → 대화형 47.3%(Typeform 260만 폼), 질문당 이탈 18%→3%, **주관식 답변 길이 2.5배·AI 가 되물으면 5배**. 우리는 입력 품질이 곧 결과 품질이라 이건 UX 이득이 아니라 제품 품질 이득이다.",
      status: "기획 중. ⚠ **속도 경쟁은 하지 말 것** — \'3분·8질문\'은 Hocoos 가, 한국은 **재밋(zaemit.com)이 \'텍스트 한 줄 3분 AI 웹사이트 빌더\'로 이미 선점**. GoDaddy Airo 로 카페 사이트를 실제 **완성**하기까지 한 리뷰어는 프롬프트 33개·4시간 45분을 썼다 — 초안 20초는 의미가 없다. 가장 방어 가능한 패턴은 알리바바 万小智의 **\'블라인드박스식 생성과 결별 — 이해한 내용을 문서로 확인받은 뒤에 짓는다\'**. 저장 위치는 sites.inferred.profile → **lib/schema.ts 무변경 = Opus·ultracode 불필요.**",
      next: "회장님 결정 4건 — ①폼+대화 혼합으로 갈지 ②온보딩에도 음성 답변을 넣을지 ③\'가게 카드\' 확인 화면을 넣을지 ④스토리 넛지 되묻기 2번(story-followup). 확정 시 세션 2~3개(Sonnet).",
      needs: ["50~60대 사장님 대상 — 음성 답변 + 선택지 버튼 병행 필수(순수 타이핑 챗은 오히려 이탈)", "진행 표시(3/6) 필수 — 언제 끝나는지 모르면 대화형 이점이 사라짐"],
      docs: [{ label: "★★ 이야기 엔진 프로토타입 v2 — 60초 영상·대본 엔진·원가표", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }, { label: "★ 이야기 엔진 프로토타입 (눌러보는 데모)", href: "/plandept/docs/story-engine-proto-2026-09-05.html", type: "html" }, { label: "★ 3분 인터뷰 → 가게 두뇌 설계", href: "/plandept/docs/ai-interview-profile-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "회장님 \'3분 대화로 홈페이지 완성 + 맥락 기능\' 제안 → 12개 서비스 실측 조사 + 저장소 확인 후 \'결과물은 홈페이지가 아니라 프로필\'로 재정의" }],
      side: "이 프로필이 8군데를 먹여 살린다 — ①사이트 생성 ②스토리 말투 ③인스타·쓰레드 캡션 ④**네이버 블로그 초안(가게마다 두뇌가 달라 문장이 갈라짐 → dup-guard 핵심 부품)** ⑤위젯 문구 ⑥FAQ 자동 생성(→geo-aio, AI 브리핑 인용) ⑦사이트 AI 상담원(万小智가 기본 탑재한 그 기능) ⑧견적 문의 답변 초안(Durable Lead Agent). 특히 ⑤\'안 하는 일\'은 AI 가 없는 서비스를 지어내는 것을 사장님 입으로 막는 장치 — 조사한 어떤 서비스도 안 한다. 비용은 인터뷰 10턴 20~50원 1회성.",
    },
    {
      id: "story-followup", title: "스토리 넛지에 \'되묻기 2번\' 붙이기", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "음성 30초 → AI 가 딱 2번만 되묻는다(\'몇 평이었어요?\' → \'손님이 제일 좋아한 부분은요?\') → 완성. 한 턴에 질문 1개, 최대 2번, **\'그냥 이대로 올릴게요\' 버튼 항상 노출**, 되묻는 내용은 업종별로 다르게(인테리어=평수·기간·자재 / 미용=시술·소요시간 / 카페=신메뉴·재료).",
      why: "되묻기를 붙이면 답변 길이가 5배가 된다(조사 수치). 그러면 ①300자 짧은 글 문제 해결 ②**구체적 수치와 본인 경험이 자동으로 들어가 네이버가 요구하는 \'솔직한 경험\'·\'독창성\'을 충족 → 저품질 방어** ③가게마다 되묻는 내용이 달라져 중복 문서 위험 감소. 비용은 AI 호출 2회 추가 = 건당 3원 미만.",
      status: "기획 중. 실존 선례 확인 — **Remento**(주 1회 문자 → 링크 탭 → **음성 답변** → Speech-to-Story 로 산문 변환 → 승인 후 인쇄, 페이지 QR 로 원본 음성 재생, $99/년)가 우리 스토리 넛지와 거의 같은 구조다. 다른 건 그들은 책을, 우리는 홈페이지·SNS 를 만든다는 것뿐 — **이 모델이 실제로 팔린다는 증거**. Storyworth(글로 답변, $99/년), Elicito AI(답에 따라 질문 분기), Ghostwriter 에이전트(한 턴에 질문 1개 원칙)도 참고.",
      next: "스토리 넛지 N2(녹음·AI·게시) 세션에 함께 넣을지 결정.",
      docs: [{ label: "★★ 이야기 엔진 프로토타입 v2 — 60초 영상·대본 엔진·원가표", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }, { label: "★ 이야기 엔진 프로토타입 (눌러보는 데모)", href: "/plandept/docs/story-engine-proto-2026-09-05.html", type: "html" }, { label: "3분 인터뷰 → 가게 두뇌 설계 (6장)", href: "/plandept/docs/ai-interview-profile-2026-09-04.md", type: "md" }, { label: "스토리 넛지 결정 v3", href: "/plandept/docs/story-nudge-decisions-2026-09-05.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "회장님 \'AI 와 대화하면서 블로그 글쓰기\' 제안 → 인터뷰형 글쓰기 도구 조사 후 되묻기 2번으로 설계" }],
    },
    {
      id: "voice-onboarding", title: "말로 만드는 홈페이지 — 음성 온보딩 (빈 자리)", stage: "idea", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "site-brain 의 6문항을 타이핑 대신 **말로** 답한다. 온보딩과 스토리 넛지가 같은 음성 파이프라인을 쓴다.",
      why: "조사 결과 **\'말로 답하면 홈페이지가 만들어지는\' 전용 서비스는 세계적으로 확인되지 않았다.** Wegic 은 채팅창 받아쓰기뿐, 재밋은 생성 **후** 음성 편집, Remento 는 음성 답변이 성숙하지만 **책이지 홈페이지가 아니다**. 우리는 이미 음성 파이프라인을 기획해 뒀으므로 부품을 재사용하면 된다. 50~60대 사장님에게 타이핑보다 말이 압도적으로 쉽다.",
      status: "아이디어. site-brain 과 같이 나가는 게 자연스럽다. ⚠ 안드로이드 카톡 인앱 브라우저는 마이크가 안 되므로(스토리 넛지 v1 조사) Chrome 유도 화면 재사용 필요.",
      next: "site-brain 확정 시 함께 결정.",
      docs: [{ label: "3분 인터뷰 → 가게 두뇌 설계 (8장)", href: "/plandept/docs/ai-interview-profile-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-04", t: "대화형 빌더 12곳 조사 중 빈 자리로 확인" }],
    },

    {
      id: "positioning", title: "★★ 포지셔닝 전환 — 홈페이지 회사가 아니라 \'가게 이야기 회사\'", stage: "planning", area: "영업·가격", decision: "대기",
      owner: "회장님 + 기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "재밋·홈온과 \'사이트 만들기\'로 싸우지 않는다. 1층 홈페이지는 비기기만 하고, 승부는 2층 **이야기 엔진**(업종별 질문 100개 → 매주 10개 → 음성 답변 → AI 되묻기 2회 → 초안)에서 본다. 경쟁 상대를 **Remento(remento.co)** 로 바꾼다.",
      why: "회장님 판단 — \'재밋이 너무 잘 나왔고 홈온과도 경쟁이 힘들다. Remento와 경쟁해야 할 것 같다.\' 참모 확인 결과 맞다: 재밋은 한 줄로 3분 사이트를 무료~$7.99 에 만들지만 **이야기·블로그·SNS 기능이 아예 없다**. 홈온은 로고·명함·도장까지 주지만 **SNS 자동 게시가 없다**. Remento 는 주 1회 질문 → 음성 답변 → 책을 연 $99 에 팔지만 **가족용이라 결과물이 팔리지 않는다**. → 한 문장: **Remento 는 가족이 읽을 이야기를, 온스토리는 손님이 읽을 이야기를 만든다.** 같은 구조인데 결과물이 매출을 만든다는 것이 연 14만 원과 연 59만 원의 차이다.",
      status: "기획 중. ⚠ 가격이 넷 중 제일 비싸다(588,000원/년) — 사이트만 놓고 보면 재밋이 무료이고 더 예쁘다. **이야기 엔진이 없으면 이 가격은 안 팔린다.** 판매 문장은 \'홈페이지를 드립니다\'가 아니라 \'매주 사장님 대신 이야기를 만들어 네 곳에 뿌리고, 1년 뒤 책으로 묶어 드립니다\' 여야 한다.",
      next: "회장님 승인 → 랜딩 문구·시연 대본을 이 축으로 다시 씀.",
      docs: [{ label: "★★★ 최종 실행 기획서 (멘트·기술점검·이미지뱅크·STEP 0~8)", href: "/plandept/docs/onstori-master-plan-2026-09-05.md", type: "md" }, { label: "★★★ 최종 실행안 프로토타입 (카피 12안·영상 후처리·정책)", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }, { label: "★★ 이야기 엔진 프로토타입 v2 — 60초 영상·대본 엔진·원가표", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }, { label: "★ 이야기 엔진 프로토타입 (눌러보는 데모)", href: "/plandept/docs/story-engine-proto-2026-09-05.html", type: "html" }, { label: "해외 AI 홈페이지 벤치마크", href: "/plandept/docs/global-ai-builder-benchmark-2026-09-04.md", type: "md" }],
      history: [{ d: "2026-09-05", t: "회장님 \'재밋이 너무 잘 나왔다, Remento 와 경쟁해야 할 것 같다\' → 참모가 세 서비스 실물 확인 후 3층 구조로 정리" }],
    },
    {
      id: "industry-picker", title: "★ 업종 고르기 화면 — 대분류 8 × 세부업종 48 + 확인 UX", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "AI 가 먼저 추천하고(\'인테리어 · 주거 리모델링 맞나요?\') 사장님이 [맞아요] 또는 [다른 업종]으로 확정한다. 대분류 8개 타일 → 세부업종 칩. **고르는 즉시 그 업종의 질문 3개를 보여준다.** 설정에서 나중에 바꿀 수 있고, 바꿔도 이미 쓴 이야기는 남는다. 범위 밖은 \'그 외 · 직접 입력\'.",
      why: "⚠ **회장님이 가장 중요하다고 지목한 부분.** 업종이 틀리면 질문 100개가 통째로 틀린다. 지금은 lib/generate.ts 가 \'하는 일 한 줄\'로 자동 분류하고 사장님은 그 결과를 **보지도 고치지도 못한다**(저장소 확인). 그리고 \'인테리어\'만으로는 부족하다 — 주거 리모델링이면 \'몇 평이었어요?\', 도배·장판이면 \'벽지는 몇 롤 들어갔어요?\' 가 되어야 질문이 그 가게 것이 된다. 고르는 즉시 질문 3개를 보여주는 것이 결정적 — 설명 열 줄보다 질문 세 줄이 낫다.",
      status: "기획 중. 프로토타입에서 실제로 눌러볼 수 있음(데모 1). 대분류 8: 인테리어·시공 / 수리·설비 / 미용·뷰티 / 카페·음식점 / 전문·상담 / 건강·운동 / 교육·공방 / 그 외. **lib/schema.ts 무변경**, config/industries.ts 확장 + 화면 1개.",
      next: "회장님 승인 → 세션 2개(Sonnet). 세부업종 48개 목록은 참모가 확정해 전달.",
      docs: [{ label: "★ 프로토타입 데모 1 — 직접 눌러보기", href: "/plandept/docs/story-engine-proto-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 \'해당 업종을 누르면 업종 선택이 제대로 이뤄져야 한다\' → 2단계 체계 + 확인 UX 설계" }],
    },
    {
      id: "question-bank", title: "★ 질문 은행 — 업종별 100개 (3막 × 난이도 3단계)", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "업종마다 100개. **1막·시작 30 / 2막·지금 50 / 3막·앞으로 20**, 각 질문에 난이도(30초 사실 / 1분 사연 / 2분 생각). 매주 10개를 카드로 제시하되 화면에는 **3장만 크게**, 나머지 7장은 [더 보기]로 접는다. 난이도는 주 단위로 깊어진다 — 1~4주차는 30초 질문만, 5주차부터 사연, 3개월 뒤 생각 질문. \'오늘은 직접 쓸래요\' 항상 노출.",
      why: "회장님 안 \'AI 로 질문 100개를 뽑아 초기·중기·말기 중 10개씩 제공\'의 구현안. ⚠ **\'말기\'라는 말은 쓰지 않는다 — 가게에 말기는 없다(폐업이 말기다).** 인생 3단계를 시작/지금/앞으로 로 번역했다. ⚠ **런타임에 AI 가 매번 뽑으면 안 된다** — 이상한 질문이 섞이고 비용이 들고, 무엇보다 가게마다 같은 질문이 나가면 답변도 비슷해져 유사문서가 된다. 정답은 **미리 뽑아 사람이 검수한 100개를 은행에 저장 + 가게 두뇌(site-brain)로 표현만 1회 개인화**.",
      status: "기획 중. **인테리어 100개는 참모가 이미 다 썼다**(프로토타입에서 전문 확인 가능 — 평수·내력벽·준공·하자보수 같은 실제 현장 어휘 사용). 확장 구조: **공통 60 + 업종 40**, 공통 60개는 슬롯 치환으로 업종마다 다르게 읽힌다({작업}=시공/시술/메뉴 준비, {현장}=현장/자리/매장, {도구}=공구/가위/머신, {단위}=평수/시간/잔 수). 48업종 × 100개를 다 쓰지 않아도 된다.",
      next: "회장님 승인 → 인테리어·미용·카페 3업종 300개 먼저. 나머지는 실제로 팔리는 업종부터.",
      docs: [{ label: "★★ 이야기 엔진 프로토타입 v2 — 60초 영상·대본 엔진·원가표", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }, { label: "★ 프로토타입 — 인테리어 100개 전문", href: "/plandept/docs/story-engine-proto-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 \'AI 로 질문 100개, 초기·중기·말기 10개씩\' → 3막·난이도 2축 구조로 설계, 인테리어 100개 실제 작성" }],
      side: "이 슬롯 치환 표가 **dup-guard 의 절반**이다. 질문이 가게마다 갈라지면 답변이 갈라지고, 답변이 갈라지면 AI 문장도 갈라진다. 네이버가 원본 하나만 남기고 나머지를 복사글 처리하는 사고를 **질문 설계 단계에서** 막는 게 사후 중복 검사보다 훨씬 싸다.",
    },
    {
      id: "story-book", title: "1년 채우면 «우리 가게 이야기책» — 유지의 이유", stage: "idea", area: "영업·가격", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "52주를 채우면 쌓인 이야기를 책으로 묶어 인쇄해 드린다. 대시보드에 진행 막대(100개 중 27개), 3막별 진행도, 연속 주 표시.",
      why: "Remento 가 **연 $99 에 파는 것이 바로 그 책**(8×10인치 컬러 하드커버, 최대 380쪽, 페이지마다 QR 로 원본 음성 재생)이다. 우리는 그걸 **유지 보상으로 준다.** 1년 결제(588,000원)를 붙잡는 이유가 \'홈페이지를 계속 쓰려고\'가 아니라 **\'책이 두 달 남았으니까\'** 가 된다. 인쇄 원가 권당 2~3만 원 = 12개월 매출의 5% 미만.",
      status: "아이디어. 2주 체험으로 10~14편이 쌓이면 이미 해지가 어려워진다(락인). 책은 그 위에 1년치 락인을 얹는 장치.",
      next: "가격 확정(pricing) 논의에 함께 올림. 인쇄 업체는 나중에.",
      docs: [{ label: "★ 프로토타입 — 진행률·이야기책 화면", href: "/plandept/docs/story-engine-proto-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "Remento 제품 확인 중 착안" }],
    },
    {
      id: "no-login-link", title: "로그인 없이 녹음 — 문자 링크 두 번이면 녹음 중", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "문자로 온 링크를 누르면 **바로 녹음 화면**. 카카오 로그인은 **게시 직전 한 번**으로 미루고, 그 뒤 기기를 기억한다. 링크에는 서명 토큰을 넣어 소유자만 열리게 한다.",
      why: "⚠ **기존 결정(카카오 로그인 게이트)을 바꾸자는 제안이다.** Remento 의 카피가 정확하다 — **\'앱 없음. 로그인 없음. 비밀번호 없음. 두 번 누르면 녹음 중.\'** 50~60대 사장님에게 로그인 화면은 그 자리에서 이탈 사유다. 녹음까지의 마찰을 0 으로 만들고, 인증은 \'게시\'라는 되돌릴 수 없는 행동 직전에만 건다.",
      status: "기획 중. 스토리 넛지 v3 에서 확정한 \'카카오 로그인\'과 충돌하므로 회장님 재결정 필요. 절충안: 첫 회만 카카오 로그인 → 이후 기기 기억(쿠키) → 녹음은 무조건 바로.",
      next: "회장님 재결정 1건.",
      docs: [{ label: "★ 프로토타입 데모 3", href: "/plandept/docs/story-engine-proto-2026-09-05.html", type: "html" }, { label: "스토리 넛지 결정 v3", href: "/plandept/docs/story-nudge-decisions-2026-09-05.md", type: "md" }],
      history: [{ d: "2026-09-05", t: "Remento 마찰 제거 카피 확인 후 제안" }],
    },

    {
      id: "video60", title: "★★ 60초 영상 — 유튜브 쇼츠 · 인스타 릴스 자동 발행", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "사장님이 폰으로 60초 세로 영상을 찍으면 ①영상은 유튜브 쇼츠·인스타 릴스로 자동 ②말한 내용은 글로 정리되어 편집 후 홈페이지·인스타·쓰레드로 자동, 네이버는 복사. 두 가지 진입 — **[대본 만들고 대답하기]**(AI가 대본을 써주면 읽기만) / **[바로 질문에 대답하기]**(카테고리→질문 10개→고르기→녹화).",
      why: "회장님 판단 — \'고객이 핸드폰으로 하루 60초, 혹은 주 1회 60초만 찍어 올리면 이 서비스는 월 49,000원 이상의 가치가 있다.\' 근거 확인: 숏폼 하루 1회 이상 시청 **82.5%**, 유튜브 쇼츠 시청률 **82.2%**(릴스 57.4%·틱톡 22.4%·네이버 클립 11.9%), 숏폼 시청 후 **62.6%가 제품·서비스를 검색**하고 63.0%가 상세페이지를 클릭한다(2026 NPR). 그리고 유튜브만 가진 것 — **남는다.** 릴스는 사흘이면 흘러가지만 유튜브는 검색으로 계속 발견되어 주 1회 60초씩 1년이면 **52편의 검색 자산**이 된다.",
      status: "기획 중. ⚠ 유튜브 함정 2개 — ①**구글 감사(audit) 통과 전에는 API 업로드가 전부 비공개로 잠긴다** ②**채널을 우리가 대신 만들 수 없다**(API에 채널 생성 기능 없음) → 온보딩 3분 안내로 손잡고 끝내주는 수밖에 없고 그 3분이 곧 상품. 쿼터는 videos.insert 하루 100건(문서 기준, 실제 7건 사례 보고 있음). 세로 3분 이하면 자동 쇼츠 판정 — 해시태그 불필요. 틱톡은 감사 전 \'나만 보기\' 영구 고정이라 MVP 제외 권고. 네이버 클립·카카오는 업로드 API 자체가 없음.",
      next: "회장님 승인 → Meta 심사와 **유튜브 감사를 오늘 동시 신청**. 심사 8~12주 동안 중계 서비스(계정당 월 $6, 100명이면 월 40만 원)로 시연.",
      needs: ["유튜브 감사 신청(오늘)", "사장님이 직접 유튜브 채널 생성 — 온보딩 위저드 필요", "영상 압축 파이프라인(ffmpeg)"],
      docs: [{ label: "★★★ 최종 실행 기획서 (멘트·기술점검·이미지뱅크·STEP 0~8)", href: "/plandept/docs/onstori-master-plan-2026-09-05.md", type: "md" }, { label: "★★★ 최종 실행안 프로토타입 (카피 12안·영상 후처리·정책)", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }, { label: "★★ 프로토타입 v2 — 두 흐름 직접 눌러보기", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 \'60초 영상 찍어 쇼츠·릴스로\' 제안 → 플랫폼별 실현성·한국 숏폼 지표 조사 후 설계" }],
      side: "⚠ 정직하게 — 소상공인이 숏폼을 해서 매출이 늘었다는 믿을 만한 통계는 **없다.** 위 숫자는 전부 \'시청 후 검색·클릭\' 간접 지표다. 시연에서 우리가 직접 만들어야 할 숫자.",
    },
    {
      id: "script-engine", title: "★ 대본 엔진 — 회장님 유튜브 프롬프트를 60초용으로 이식", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "[대본 만들고 대답하기]를 누르면 AI가 주제 선택 → 각도 선택 → 장면 한 문장 → **60초 대본(300~350자)** 을 내놓는다. 사장님은 화면에 흐르는 대본을 읽으면서 찍기만 하면 된다. 스토리텔링 고민이 사라진다.",
      why: "회장님이 주신 «유튜브 콘텐츠 기획 멀티 프롬프트 시스템»의 3단계(재료 캐기 → 설계 → 집필)를 60초·소상공인용으로 압축한 것. 사장님이 답하는 것은 **선택 두 번과 한 문장**뿐.",
      status: "기획 중. **원본에서 그대로 가져올 5가지** — ①분당 300~350자(60초=300~350자, 화면에 글자수 실시간 표시) ②추상적인 답이 오면 되묻는다(\'열심히 했습니다\'→\'그날 몇 시에 뭐 하셨어요?\'. **감정 형용사는 재료가 아니고 장면이 재료**) ③실패부터 판다(성공담은 제3자 근거 필요, 실패담은 그냥 말해도 믿는다 — \'취약성에는 진입장벽이 없다\') ④한 문장에 정보 하나·45자 초과 금지 ⑤자문자답을 리듬 축으로. **덜어낼 것** — 시청자 언어 채집(댓글·자동완성)은 사장님이 못 하므로 **우리가 대신 채운다**(그 업종 견적 문의 문장 + \'자주 받는 질문\' 3개 + 지역 검색어). **설정 카드는 안 묻는다** — site-brain(가게 두뇌)이 그 자리를 이미 채운다.",
      next: "회장님 승인 → 세션 2개(Sonnet). site-brain 선행 필수.",
      needs: ["site-brain(가게 두뇌) 선행 — 설정 카드 역할"],
      docs: [{ label: "★★★ 최종 실행안 프로토타입 (카피 12안·영상 후처리·정책)", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }, { label: "★★ 프로토타입 v2 — 흐름 B 직접 눌러보기", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님이 유튜브 대본 프롬프트 전문 제공 → 60초용으로 압축 설계" }],
      side: "원본 자가검사 1번 **\'다른 사람이 그대로 읽어도 말이 되면 불통과\'** 를 그대로 쓴다. 사장님 고유의 장면·숫자가 없는 대본은 내보내지 않고 되묻기를 한 번 더 한다. **이 검사 하나가 \'AI 티\'의 대부분을 잡는다.**",
    },
    {
      id: "story-category", title: "이야기 카테고리 6개 — 누르면 질문 10개", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "**시작 이야기 · 경험 이야기 · 나만의 스토리 · 실적 이야기 · 손님 이야기 · 요즘 이야기.** 카테고리를 누르면 그 주제 질문 10개가 나오고 하나를 골라 답한다. 앞의 다섯은 한 번씩 채우면 되는 자산이고, **\'요즘 이야기\'만 매주 반복**된다.",
      why: "회장님이 직접 제시한 카테고리 이름을 거의 그대로 썼다([시작이야기][경험이야기][나만의스토리][실적이야기][최근손님이야기]). 3막 구조(시작/지금/앞으로)보다 **사장님 눈에 훨씬 직관적**이다. 3막은 내부 분류로만 남긴다.",
      status: "기획 중. question-bank(업종별 100개)를 카테고리로 재배열한 것. 프로토타입 v2 에서 6개 전부 눌러볼 수 있음.",
      next: "question-bank 와 같은 세션.",
      docs: [{ label: "★★ 프로토타입 v2 — 흐름 A", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 카테고리 안 제시 → 6개로 정리" }],
    },
    {
      id: "image-bank-ai", title: "★ 이야기 이미지 — 생성하지 않고 뱅크에서 꺼내 쓰기", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "**이야기마다 AI로 이미지를 새로 뽑지 않는다.** 미리 만들어 둔 배경 뱅크에서 꺼내 **이야기 한 줄만 얹는다.** 한 장에서 1:1·4:5·9:16 세 가지가 나오고, 가게마다 글이 다르니 결과물도 매번 다르다.",
      why: "회장님 지시 — \'글을 보고 이미지 생산은 하지 않고, 이미지뱅크 활용하자. 이미지 뱅크만 활용해도 원가 대폭 절감 가능.\' 맞다: **고객 1인 월 원가 250원 → 67원**(49,000원의 0.5% → **0.14%**), 하루 3건 상한도 2,830원 → 756원. 뱅크 짓는 비용은 **256장에 약 1,024원 일회성**.",
      status: "기획 중. **이미 있는 것을 그대로 쓴다** — image_bank 테이블(승인 638장)과 pickImage(업종,무드,자리,{text}) 매칭 함수가 이미 돌아간다(태그 점수 + used_count 배분 + 히어로 중복 회피 + 플레이스홀더 폴백). **role 에 \'story\' 하나만 추가**하면 되고 **lib/schema.ts 무변경 = Opus·ultracode 불필요.** 핵심 발견 2개 — ①**\'고르는\' 데는 돈이 안 든다**: 이미 글 4종을 만드는 호출이 있으니 그 응답에 imageTags·cardLine 두 필드만 더 요구하면 **추가 호출 0회·비용 0원** ②**배경 1장으로 무한히 만든다**: 배경 + 이야기 한 줄 + 크롭 3종을 @vercel/og(ImageResponse)로 서버에서 합성 — 이것도 0원.",
      next: "회장님 결정 4건 — ①생성 모델(Flux Schnell 4원 vs 나노바나나2 Lite 배치 23원) ②규모(256장 1,024원 vs 2,880장 11,520원) ③\'AI로 만든 배경\' 표기 여부 ④예전 사진 재활용 허용 여부. 세션 I1~I4(전부 Sonnet).",
      docs: [{ label: "★★★ 최종 실행 기획서 (멘트·기술점검·이미지뱅크·STEP 0~8)", href: "/plandept/docs/onstori-master-plan-2026-09-05.md", type: "md" }, { label: "★ 이야기 이미지 — 뱅크 활용 구현안", href: "/plandept/docs/image-bank-story-spec-2026-09-05.md", type: "md" }, { label: "★★ 프로토타입 v2 — 이미지 뱅크 데모", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 이미지 뱅크 제안 → 공식 가격표 조사" }, { d: "2026-09-05", t: "회장님 \'생성 말고 뱅크만\' 지시 → 원가 250→67원, lib/bank.ts 실측 후 구현안 작성" }],
      side: "⚠ **뱅크에 \'장면 사진\'을 넣지 않는다.** 완성된 거실 같은 걸 넣으면 실제 시공 사진으로 오해받아 표시광고법 문제가 된다. 대신 **글자를 얹을 추상적 배경**(나뭇결·콘크리트·타일 질감·색면·흐린 공구)만 넣는다. 이러면 오해 소지가 애초에 없고, **업종을 잘게 나눌 필요도 없어져** 48업종 4,800장이 아니라 **8묶음 256장**으로 끝난다. 생성 프롬프트에 \'텍스트를 얹을 여백을 왼쪽 아래에 크게 비울 것\'을 반드시 넣는다. 사장님 사진이 언제나 1순위, 뱅크는 사진 못 찍은 날의 안전망 — 이야기가 쌓일수록 뱅크를 덜 쓰게 된다.",
    },    {
      id: "x-paid", title: "X(트위터) 게시 — 유료 옵션으로만", stage: "planning", area: "영업·가격", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "X 에는 **링크 없이 글만** 내보내고 사이트 주소는 프로필에 걸어둔다. 상위 요금제 특전으로 제공.",
      why: "회장님 안 — \'유료 고객은 X 에도 게재 가능하게.\' 원가 확인: 게시 **$0.015(20원)**, 그런데 **링크를 넣으면 $0.20(272원)으로 13배**가 된다(X API 공식). 링크 없이 월 8건이면 160원이라 특전으로 얹을 만하지만, 링크 포함으로 하루 3건 상한을 다 쓰면 **월 24,480원 — 요금의 절반**이 날아간다.",
      status: "기획 중. 링크가 꼭 필요하면 별도 과금 항목으로.",
      next: "가격 확정(pricing) 논의에 함께.",
      docs: [{ label: "★★ 프로토타입 v2 — X 원가표", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 제안 → X API 공식 단가 확인 후 링크 분리 설계" }],
    },
    {
      id: "daily-limit", title: "하루 3건 상한 — 채널마다 다르게 잠그기", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "홈페이지는 하루 3건까지 열고, **인스타·쓰레드는 하루 1~2건, 네이버 블로그는 하루 1건**으로 채널마다 따로 잠근다.",
      why: "회장님 안 \'하루에 최대 3건까지 등록 가능하게\'의 안전한 구현. 같은 날 몰아 올리는 것이 계정을 태우는 가장 흔한 사고다 — Meta 는 \'높은 빈도의 봇 동작\'을 금지하고, 네이버는 하루 5개 이상 발행을 위험 신호로 본다. 내 사이트(홈페이지)는 제재가 없으니 무제한에 가깝게 열어도 된다.",
      status: "기획 중. dup-guard 와 한 묶음.",
      next: "autopost·video60 세션에 포함.",
      docs: [{ label: "★★ 프로토타입 v2", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 제안 → 채널별 차등 상한으로 설계" }],
    },
    {
      id: "text-polish", title: "직접 쓴 글도 반드시 AI 가공", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "사장님이 손으로 쓴 글도 음성과 **똑같은 파이프라인**을 탄다 — 되묻기 → 다듬기 → [다듬은 글]/[제가 쓴 글] 토글 → 4종 변환. 입력 방법만 다를 뿐이다.",
      why: "회장님이 직접 써보시고 남긴 지적 — \'가공이 되었으면 좋겠어, 이 부분 정말 중요해.\' 지금은 글로 쓰면 그대로 올라간다. 말한 것만 다듬고 쓴 것은 안 다듬으면 품질이 두 갈래로 갈린다.",
      status: "기획 중. 구현은 간단 — 입력원(음성/텍스트)만 다르고 이후 함수는 공유.",
      next: "흐름 A 세션에 포함.",
      docs: [{ label: "★★ 프로토타입 v2", href: "/plandept/docs/story-engine-proto-v2-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 직접 사용 후 지적" }],
    },

    {
      id: "caption-burn", title: "★★ 자막 번인 + 무음 컷편집 — 영상 1건 13원", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "60초 영상을 받아 ①단어 단위 타임스탬프로 **자막을 태우고** ②«어…» 하고 멈춘 무음 구간을 **잘라 붙인 뒤** 쇼츠·릴스로 발행. Cloud Run 에 ffmpeg 컨테이너 하나.",
      why: "회장님 판단 — \'그냥 영상만 올라오는 것과 자막 있는 기본 컷편집 영상은 차원이 다르다.\' 맞고, **값이 거의 안 든다**(13원/건). 근거: Verizon×Publicis 조사(미국 성인 5,616명) **80%가 \'자막 있으면 끝까지 볼 가능성 높다\'**, 모바일 광고 실측 **회상 +8%·브랜드 연결 +13%**. PLOS ONE 2024(168명 아이트래킹)는 무음 시청 시 자막을 훨씬 열심히 읽지만 인지부하가 급증함을 보임 → **한 화면 1~2줄·큰 글씨**가 중요. ⚠ 흔히 쓰는 \'85% 무음 시청\'은 **2016년 페이스북 기준**이라 인용 금지.",
      status: "기획 중. 원가: 음성 인식(단어 타임스탬프) **AssemblyAI Universal-2 3.4원**(⚠ OpenAI 신규 모델은 단어 타임스탬프 미지원 — whisper-1 만 됨, Gemini 는 타임스탬프 켜면 정확도 저하 명시) + 인코딩 **Cloud Run 2원**(무료 티어 월 3,000건). 관리형 API 대안 ZapCap $0.10/분(134원, 한국어 CJK 렌더링 명시) — 자체 구축의 10배. Vercel 함수는 **요청 바디 4.5MB 제한** 때문에 영상을 직접 못 받으므로 R2 presigned URL 경유 + 별도 워커가 정답.",
      next: "회장님 승인 → 세션 2개(Sonnet). 흐름 A 와 같은 시기.",
      needs: ["컨테이너에 한글 폰트 임베드(없으면 자막 통째로 깨짐)", "어절 기준 줄바꿈 직접 구현"],
      docs: [{ label: "★★★ 최종 실행 기획서 (멘트·기술점검·이미지뱅크·STEP 0~8)", href: "/plandept/docs/onstori-master-plan-2026-09-05.md", type: "md" }, { label: "★★★ 최종 실행안 프로토타입 (카피 12안·영상 후처리·정책)", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 \'자막·컷편집 검토\' 지시 → 기술·원가·정책 전수 조사" }],
      side: "⚠ **한국어 자막의 진짜 리스크는 줄바꿈이다.** 표준 도구 libass 는 한글 단어 중간에서 줄을 끊고(이슈 #694, 3년째 미해결), 해법으로 알려진 wrap_unicode 는 한국어에서 오히려 형태소 경계로 끊어 더 나빠진다. **답: 라이브러리에 맡기지 말고 앱에서 어절(띄어쓰기) 기준으로 직접 나눠 \\N 삽입.** 줄당 12~16자면 충분하고 형태소 분석기는 불필요. 무음 제거는 한국어 종결어미(~요/~습니다)가 에너지 급감해 잘리므로 **앞뒤 150~250ms 패딩 + 20~40ms 크로스페이드** 필수.",
    },
    {
      id: "no-avatar", title: "얼굴→아바타 교체는 하지 않는다 (대안: 손·작업물 촬영 템플릿)", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "얼굴을 캐릭터로 바꾸는 기능은 **안 만든다.** 대신 «손과 작업물만 나오는 촬영» 템플릿을 기본 제공한다.",
      why: "회장님 문의에 대한 답. 세 가지 이유 — ①**값이 620배**: HeyGen 등 아바타 API 초당 $0.10 → 60초 **8,064원**(자막+컷편집 13원 대비). 월 49,000원 요금제가 무너진다 ②**품질이 안 난다**: 정면 고정 발화는 그럴듯하나 소상공인 영상 특유의 손동작·상체 움직임·매장 배경에서 무너지고 한국어 립싱크도 약함 ③**팔려는 것을 지운다**: 소상공인 영상의 자산은 \'진짜 사장님\'이라는 진정성인데 아바타가 바로 그걸 없앤다.",
      status: "기획 중. 정책 확인 — 유튜브는 «실제 인물이 하지 않은 말을 한 것처럼 보이게 하는 것»을 **공시 의무 대상**으로 명시하고 반복 미공시 시 라벨 강제·수익화 제외까지 간다. 반대로 **«본인 목소리를 복제해 더빙하는 것»은 공시 면제**로 명시 — 목소리는 되고 얼굴은 안 된다는 선이 분명하다. 완전한 카툰/애니 스타일화는 비사실적 콘텐츠로 면제 가능성 있으나 검토 보류.",
      next: "«손만 나오는 촬영» 템플릿을 흐름 A 촬영 안내에 포함.",
      docs: [{ label: "★★★ 최종 실행안 프로토타입 (카피 12안·영상 후처리·정책)", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 문의 → 원가·품질·정책 3중 검토 후 미채택 권고" }],
      side: "«얼굴 부담»이라는 진짜 니즈는 아바타(8,064원)가 아니라 **촬영 가이드(13원)** 로 훨씬 싸고 안전하게 풀린다.",
    },
    {
      id: "no-aivideo", title: "목소리만으로 AI 영상 생성은 하지 않는다 (대안: 사진 슬라이드)", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "AI 로 영상을 통째로 만들어 주는 기능은 **안 만든다.** 대신 **사장님 사진 + 본인 목소리 + 자막** 슬라이드 영상(3~5원)을 제공한다.",
      why: "회장님 문의에 대한 답. **값보다 구조가 문제다** — 지금 AI 영상 생성은 **1회 최대 8초**라 60초를 만들려면 여덟 번 나눠 만들어야 하고 **사장님 얼굴·매장·조명이 매번 달라진다.** 이어붙이기 기능이 있어도 갈수록 뭉개진다. 값도 Veo 3.1 1080p **32,256원**, Lite 4,032원, Kling 5,645원으로 전부 요금제를 넘긴다.",
      status: "기획 중. 스톡 영상 + AI 목소리 방식(245원)도 **보류** — ⚠ Coverr 라이선스는 \'영상 편집 플랫폼의 일부로 제공\'을 명시 금지하므로 우리 서비스에 쓰면 위반 소지. Pexels(시간당 200회·월 20,000회, 출처 표기 필수)·Pixabay(이미지 핫링크 금지, 서버 다운로드 필수)만 조건부 사용 가능. 게다가 아래 정책 리스크가 크다.",
      next: "사진 슬라이드 방식만 3차로.",
      docs: [{ label: "★★★ 최종 실행안 프로토타입 (카피 12안·영상 후처리·정책)", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 문의 → 단가·클립 길이 제약·라이선스 검토 후 미채택" }],
    },
    {
      id: "authenticity", title: "★★ 유튜브 «비진정성 콘텐츠» 정책 — 제품 설계 최상위 제약", stage: "planning", area: "법무·정책", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "제품 규칙 4개를 처음부터 박는다 — ①이야기마다 **사장님이 직접 찍은 소재 최소 1개 강제** ②**본인 목소리 우선** ③자막 스타일·전환·색을 **가게마다 다르게 배정**해 시각적 지문을 흩뜨림 ④같은 배경이 여러 고객에게 몰리지 않게 **중복 방지**.",
      why: "⚠ **이 사업의 최대 리스크는 기술도 원가도 아니라 플랫폼 정책이다.** 유튜브가 2025-07 「반복 콘텐츠」를 「**비진정성 콘텐츠**」로 확대하며 명시: «대량 생산되었거나, 일반적이거나, 반복적이거나, 조작적이지 않을 것», «**대량 생산 인상을 주는 일반적·비독창적 템플릿으로 만든 AI 콘텐츠**» 금지 — 단 «제작자 고유의 통찰이나 관점»이 더해지면 예외. **모든 고객 영상이 같은 템플릿으로 나오면 정면으로 걸린다.**",
      status: "기획 중. **인스타는 반대로 우리 방향을 원본으로 인정한다** — Meta 2026-04 발표: «고유한 텍스트, 창의적 편집, **보이스오버**를 더하면 원본 창작물». 즉 자막·컷편집은 원본성을 깎는 게 아니라 **더한다.** 반면 타인 영상 재업로드·속도만 변경은 추천 노출에서 제외. 위험도: 사장님 촬영본+자막 **낮음** / 사진+본인 목소리 **중간** / 공용 스톡+AI 목소리 **높음** / 순수 AI 생성 **매우 높음**.",
      next: "dup-guard·caption-burn 세션에 규칙 4개를 요구사항으로 포함.",
      docs: [{ label: "★★★ 최종 실행안 프로토타입 (카피 12안·영상 후처리·정책)", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "영상 후처리 조사 중 최대 리스크로 확인 — 별도 항목으로 분리" }],
    },
    {
      id: "hero-copy", title: "★ 히어로 카피 확정 — «홈페이지는 텅 빈 상가입니다»", stage: "done", area: "영업·가격", decision: "확정",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "**확정** — 히어로 «홈페이지는 텅 빈 상가입니다. 스토리에는 진짜 사람이 있습니다.» / 서브 «사장님이 들려주시는 스토리가 사업을 굴러가게 만듭니다. 온스토리.» / 서브서브 4개(①60초만 말하세요 ②질문은 저희가 ③얼굴 안 나와도 됩니다 ④3년 뒤에도 검색되는 영상). 나머지 14개 문구는 랜딩 하위·문자·명함·전단용으로 보관.",
      why: "회장님 지시. **참모 추천은 방향1-A1 «홈페이지를 만들어 드리지 않습니다. 사장님 사업이 굴러가게 만듭니다.»** — 우리가 파는 것이 무엇인지를 한 문장에서 뒤집어 말한다. **홈페이지 업체로 보이면 재밋(무료)·홈온(월 9,900)과 가격 비교를 당하지만, 마케팅 대행으로 보이면 숏폼 편집 외주 편당 62,500원과 비교된다.** 같은 서비스인데 비교 대상이 달라진다.",
      status: "기획완료. 방향 2 는 **랜딩 두 번째 화면이나 문자 첫 줄**로 — 조급함은 처음 만나는 사람에겐 부담이고 이미 관심 보인 사람에겐 결정을 앞당긴다.",
      next: "회장님이 하나 선택.",
      docs: [{ label: "★★★ 최종 실행 기획서 (멘트·기술점검·이미지뱅크·STEP 0~8)", href: "/plandept/docs/onstori-master-plan-2026-09-05.md", type: "md" }, { label: "★★★ 최종 실행안 프로토타입 (카피 12안·영상 후처리·정책)", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님이 기초 멘트 2종 제시 → 각 6개로 전개" }],
    },

    {
      id: "bank-admin", title: "★★ 이미지 뱅크 생성기 (어드민) — 숫자 넣고 버튼", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "어드민에서 **소재·톤·비율·품질·수량**을 고르면 **비용과 예상 시간이 즉시 계산**되고, 배치로 걸어두면 AI 가 **별점 1~5 + 키워드 12~20개 + 글자 얹을 자리**까지 붙여 검수 대기로 올린다. ★2 이하 자동 폐기, ★4 이상 일괄 승인.",
      why: "회장님 지시 — \'잠자기 전이나 한가할 때 이미지뱅크를 최대한 많이 만들려고 한다. 숫자 넣고 버튼만 누르면 AI 가 생성되게. 100/500/1000/3000장 + 완성 예상시간 + AI 자동 별점까지.\' 40만 원 크레딧을 3개월 안에 다 쓰는 것이 목표.",
      status: "기획 중. **예산 배분 확정안** — 대표용 2K 1,000장(69,000원) + 카드용 1K Lite 13,000장(299,000원) + AI 별점·태깅 14,000장(21,000원) + 여유 11,000원 = **40만 원에 14,000장.** 기존 638장 합쳐 약 14,600장. **처리량**: Tier 1 지출 상한이 10분당 $10 라 1K 기준 시간당 최대 1,785장 — 3,000장이면 2~4시간. 배치는 목표 24시간(48시간 초과 시 만료).",
      next: "회장님 결정 3건 — ①예산 배분 승인 ②크레딧 잔액·만료일 확인 ③Vertex AI 전환 착수. 세션 I1~I4(전부 Sonnet).",
      needs: ["Google Cloud 프로젝트 + 결제 계정 연결", "크레딧 잔액·만료일 확인"],
      docs: [{ label: "★★★ 최종 실행 기획서 (멘트·기술점검·이미지뱅크·STEP 0~8)", href: "/plandept/docs/onstori-master-plan-2026-09-05.md", type: "md" }, { label: "★★★ 프로토타입 — 어드민 생성기 직접 조작", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 자동화 지시 → 단가·한도·크레딧·용량 전수 조사 후 설계" }],
      side: "⚠⚠ **최우선 발견 — 크레딧이 새고 있을 수 있다.** 40만 원은 **Google Cloud 무료 체험 $300(90일)** 이 거의 확실한데, 구글 공식 문서에 **«$300 크레딧은 AI Studio 의 Gemini API 비용을 결제할 수 없습니다»** 라고 명시돼 있다. **지금 AI Studio 키로 뽑으면 크레딧이 안 깎이고 카드에서 나간다.** 반드시 **Vertex AI 경로**(서비스 계정 + vertexai=True)로 전환해야 하고 가격은 완전히 동일. 개발자 포럼에 같은 피해 사례 다수. **그래서 이미지 뱅크가 STEP 1 이다 — 90일 시계가 이미 돌고 있다.**",
    },
    {
      id: "story-layout", title: "★ 스토리 페이지 디자인 → 이미지 규격 확정", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "PC 본문 폭 **720px** 기준 — **대표 이미지 720×405(파일 1440×810)** / **영상 380×676 세로(파일 1080×1920)** / **사진 3장 각 232×232(파일 464×464)**. 이 디자인에서 뱅크 원본 크기가 나온다: 가로 16:9 60% · 정사각 1:1 30% · 세로 9:16 10%.",
      why: "회장님 지시 — \'이미지 크기도 PC 버전 기준으로 스토리 이미지·영상·사진이 나오게끔 디자인을 먼저 하고, 이 디자인을 기준으로 이미지뱅크 사진 크기를 정하자.\' 순서가 맞다. 화면을 먼저 정해야 낭비 없이 뽑는다.",
      status: "기획 중. 필요한 최대 크기가 1440×810 인데 1K 16:9 원본이 약 1344×768 이라 아슬아슬 → **대표용 1,000장만 2K**로 뽑는 하이브리드. 배경이 질감·색면이라 크롭해도 안 무너지는 게 전제.",
      next: "STEP 2 세션(Sonnet 2세션).",
      docs: [{ label: "★★★ 최종 실행 기획서 (멘트·기술점검·이미지뱅크·STEP 0~8)", href: "/plandept/docs/onstori-master-plan-2026-09-05.md", type: "md" }, { label: "★★★ 프로토타입 — 레이아웃 목업", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 \'디자인 먼저\' 지시 → 레이아웃 확정 후 역산" }],
    },
    {
      id: "photo-picker", title: "사진 고르기 — 10장 추천 → 3장 고정", stage: "planning", area: "제품", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "스토리를 다 쓰면 **①이야기와 겹친 키워드 많은 순 ②별점 높은 순 ③최근 덜 쓰인 순**으로 정렬한 상위 30장 중 **랜덤 10장**을 보여주고 **3장 고정 선택**. 그 가게가 최근 12편에 쓴 사진은 제외.",
      why: "회장님 지시 그대로. 그리고 **«직접 찍은 사진으로 넣으시면 이야기에 신뢰가 쌓입니다»** 문구와 [내 사진 올리기] 버튼을 추천 사진들보다 **위에, 더 크게** 둔다 — 뱅크는 못 찍은 날의 안전망이지 기본값이 아니다.",
      status: "기획 중. 추천에는 400px 썸네일만 부름(10장 300KB). GIN 인덱스로 2만 행 검색 수 밀리초.",
      next: "STEP 2 세션에 포함.",
      docs: [{ label: "★★★ 최종 실행 기획서 (멘트·기술점검·이미지뱅크·STEP 0~8)", href: "/plandept/docs/onstori-master-plan-2026-09-05.md", type: "md" }, { label: "★★★ 프로토타입", href: "/plandept/docs/story-engine-proto-final-2026-09-05.html", type: "html" }],
      history: [{ d: "2026-09-05", t: "회장님 지시 → 정렬 규칙·문구 확정" }],
    },
    {
      id: "r2-capacity", title: "서버 용량·속도 점검 — 전부 무료 범위", stage: "planned", area: "인프라", decision: "대기",
      owner: "기술참모", since: "2026-09-05", updated: "2026-09-05",
      summary: "14,000장 + 파생 3종 = **약 5.0 GB** (R2 무료 10GB 이내). 업로드 연산 56,000회 = 무료 100만 회의 5.6%. 전송은 R2 가 무료.",
      why: "회장님 질문 — \'고화질 이미지 다 쓰면 서버 용량 얼마나 찰까? 무료범위 이내 맞아? 서버 속도 느려지지 않고 빠르게 생성 및 찾기 가능하게.\' 답: **전부 무료 범위 안**이고, 3만 장까지 늘려도 약 10GB 라 월 몇 백 원.",
      status: "확인 완료. ⚠ 반드시 해야 할 것 2가지 — ①**R2 커스텀 도메인**(r2.dev 는 레이트 리밋이 걸려 개발용) ②**Cache Everything 규칙 + Cache-Control immutable**(캐시가 자동이 아님). ⚠ **Cloudflare Images 쓰지 말 것** — 사이즈 3종 온더플라이는 월 $27.5 가 매달 나가지만 사전 생성은 사실상 0원. DB 는 GIN 인덱스, 대량 적재 시 드롭 후 재생성.",
      next: "STEP 1 에 포함.",
      docs: [{ label: "★★★ 최종 실행 기획서 (멘트·기술점검·이미지뱅크·STEP 0~8)", href: "/plandept/docs/onstori-master-plan-2026-09-05.md", type: "md" }],
      history: [{ d: "2026-09-05", t: "회장님 질문 → R2·Supabase 공식 한도로 계산" }],
    },

    /* ───────────── 적용완료 ───────────── */
    {
      id: "p5-condition", title: "P5(결제) 진입 조건 변경 — 문의·미리보기·위젯 + 시연", stage: "done", area: "프로세스", decision: "확정",
      owner: "회장님", since: "2026-09-03", updated: "2026-09-03",
      summary: "선판매 게이트(사진 5건→전환 30%) 대신, 3개 기능이 프로덕션에서 돌고 실제 사장님에게 시연한 뒤 결제로 간다.",
      why: "결제보다 가치 체감이 먼저.",
      status: "DECISIONS·PLAN·sprint-plan에 기록 완료.",
      next: "—",
      docs: [{ label: "스프린트 플랜", href: "/plandept/docs/sprint-plan-2026-09-03.md", type: "md" }],
      history: [{ d: "2026-09-03", t: "확정" }],
    },
    {
      id: "cloudflare-dns", title: "onstori.com DNS Cloudflare 이전 + R2 버킷·도메인·토큰", stage: "done", area: "인프라", decision: "확정",
      owner: "회장님(참모 코칭)", since: "2026-09-03", updated: "2026-09-03",
      summary: "Spaceship → Cloudflare 네임서버, Vercel 레코드 DNS only, www 추가, R2 구독($1 알림), onstori-media/private 버킷, img.onstori.com, API 토큰, Vercel env 6개.",
      why: "R2 이전의 사람 손 준비.",
      status: "완료.",
      next: "—",
      docs: [{ label: "R2 스펙 2장 사전 준비", href: "/plandept/docs/storage-r2-spec-2026-09-03.md", type: "md" }],
      history: [{ d: "2026-09-03", t: "완료" }],
      side: "부작용: 와일드카드 서브도메인 소실 → 'wildcard' 항목.",
    },
    {
      id: "showcase-clean", title: "쇼케이스 데모 3건 제외 + 발행 사이트 날조 문구 제거", stage: "done", area: "법무·정책", decision: "확정",
      owner: "클코팀장", since: "2026-09-03", updated: "2026-09-03",
      summary: "가짜 경력·후기가 담긴 데모 시드 3건을 랜딩에서 빼고 실고객 2곳만. 발행 사이트 3곳의 '오랜 노하우' 류 문구 제거 + 프롬프트 규칙 확대 + copyModel 기록.",
      why: "리포트 '부족한 지점 9·12'.",
      status: "완료(후처리 필터는 별도 항목).",
      next: "—",
      docs: [{ label: "기술고문 리포트", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-03", t: "완료" }],
    },
    {
      id: "gap-report", title: "온스토리 vs 홈온 갭 분석 · 이기는 무기 · 로드맵 (기술고문 리포트)", stage: "done", area: "프로세스", decision: "확정",
      owner: "기술참모", since: "2026-09-02", updated: "2026-09-02",
      summary: "뼈대는 홈온의 70%, '돈 내는 이유' 층은 0%. 무기 6개(리드 엔진·스토리 SEO·공유 시트·속도·후기 링크·환불 정책). 스프린트 A~F.",
      why: "출발점 문서.",
      status: "보고 완료. 개별 항목은 각각 아이디어로 분리됨.",
      next: "—",
      docs: [{ label: "기술고문 리포트", href: "/plandept/docs/advisor-report-2026-09-02.html", type: "html" }],
      history: [{ d: "2026-09-02", t: "보고" }],
    },
    {
      id: "roles", title: "역할 규칙 — 참모는 기획만, 저장소는 회장님 수락 후에만", stage: "done", area: "프로세스", decision: "확정",
      owner: "회장님", since: "2026-09-04", updated: "2026-09-04",
      summary: "기술참모(코워크)는 기획·검토만. 클코팀장·클로드코드가 실행. 저장소(onhome/onstori)에는 참모가 직접 쓰지 않는다. '적용하자' 뒤에도 '이 메시지 보낼까요? 이 파일 넣어도 될까요?'를 먼저 묻는다.",
      why: "동시에 작업 중인 사람들이 예고 없는 파일 변경에 놀란다.",
      status: "확정. 09-04에 실수로 들어간 스펙 2건 삭제 요청 중.",
      next: "—",
      docs: [],
      history: [{ d: "2026-09-04", t: "확정" }],
    },

    /* ───────────── 폐기 · 보류 ───────────── */
    {
      id: "subdomain", title: "서브도메인 주소 체계 ({slug}.onstori.com)", stage: "dropped", area: "인프라", decision: "폐기",
      owner: "클코팀장", since: "2026-08-31", updated: "2026-09-01",
      summary: "경로 방식(onstori.com/{slug})으로 전환. 네이버 서치어드바이저가 캡차로 대량 등록 불가 → 서브도메인이면 고객 수만큼 수동 등록.",
      why: "SEO 자동화·도메인 권위 승계.",
      status: "폐기(2026-09-01 DECISIONS). 서브도메인은 본사 내부용으로만 보류.",
      next: "—", docs: [], history: [{ d: "2026-09-01", t: "폐기" }],
    },
    {
      id: "presale-gate", title: "선판매 게이트 (사진 수신 5건 → 유료 전환 30%)", stage: "dropped", area: "영업·가격", decision: "보류",
      owner: "회장님", since: "2026-08-31", updated: "2026-09-03",
      summary: "P5 진입 조건에서 빠짐. 폐기가 아니라 3개 기능 위에서 다시 진행.",
      why: "기능 없이 게이트만 재면 전환이 0.",
      status: "보류.", next: "P5 3조건 뒤.", docs: [{ label: "스프린트 플랜", href: "/plandept/docs/sprint-plan-2026-09-03.md", type: "md" }], history: [{ d: "2026-09-03", t: "보류" }],
    },
    {
      id: "worktree", title: "git worktree 병렬 세션 (클로드코드 터미널 2개)", stage: "dropped", area: "프로세스", decision: "폐기",
      owner: "회장님", since: "2026-09-02", updated: "2026-09-03",
      summary: "에디터·미리보기·문의를 병렬로 하자는 안. 처음 하는 조합이라 병합·마이그레이션 순서 리스크 → 단일 터미널 순차로.",
      why: "리스크 회피.",
      status: "폐기(단일 터미널 원칙).", next: "—", docs: [{ label: "실행 런북 (당시 병렬안)", href: "/plandept/docs/runbook-inquiry-2026-09-03.html", type: "html" }], history: [{ d: "2026-09-03", t: "폐기" }],
    },
    {
      id: "write-key", title: "스토리 작성 키 링크 (?k=8자리, 로그인 없이)", stage: "dropped", area: "제품", decision: "폐기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "넛지 v1의 인증안. v2에서 카카오 로그인(owner_id 대조)으로 대체 — 카톡 안에서 1탭이라 키보다 낫고 안전.",
      why: "회장님 판단이 맞았다.",
      status: "폐기.", next: "—", docs: [{ label: "기획 v2 2장", href: "/plandept/docs/story-nudge-plan-v2-2026-09-04.md", type: "md" }], history: [{ d: "2026-09-04", t: "폐기" }],
    },
    {
      id: "concierge", title: "카톡 음성메시지 컨시어지 (회장님이 대신 올리기)", stage: "dropped", area: "운영", decision: "폐기",
      owner: "회장님", since: "2026-09-04", updated: "2026-09-04",
      summary: "사장님이 카톡 채팅에 음성으로 답하면 회장님이 대신 올리는 안. 회장님 결정 4(카톡 음성은 글이 되지 않는다고 명시)로 폐기. 운영자 '대신 올리기' 버튼은 QA용으로만 남김.",
      why: "회장님 손이 간다.",
      status: "폐기.", next: "—", docs: [{ label: "기획 v2 0장", href: "/plandept/docs/story-nudge-plan-v2-2026-09-04.md", type: "md" }], history: [{ d: "2026-09-04", t: "폐기" }],
    },
    {
      id: "agent-kakao", title: "에이전트(헤르메스·오픈클로 등)로 카톡 개인계정 자동 발송", stage: "dropped", area: "운영", decision: "폐기",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "카카오 운영정책 위반으로 계정 정지 위험, 사장님 눈엔 스팸. 에이전트는 '발송 엑셀·명단·응답 요약 만들기'에만 쓴다.",
      why: "정책·신뢰.",
      status: "폐기(대안: 알림톡 API).", next: "—", docs: [{ label: "기획 v1 6장", href: "/plandept/docs/story-nudge-plan-v1-2026-09-04.md", type: "md" }], history: [{ d: "2026-09-04", t: "폐기" }],
    },
    {
      id: "img-gen-button", title: "편집 화면 'AI로 히어로 새로 만들기' 버튼", stage: "dropped", area: "제품", decision: "보류",
      owner: "기술참모", since: "2026-09-04", updated: "2026-09-04",
      summary: "장당 $0.134·15초·검수 문제. 뱅크 638장이 있는 동안은 '선택'만. P6 유료 옵션(하루 1회 제한)으로 재검토.",
      why: "비용·대기·품질.",
      status: "보류(P6).", next: "P6.", docs: [{ label: "히어로 기획 3-1", href: "/plandept/docs/hero-image-picker-2026-09-04.md", type: "md" }], history: [{ d: "2026-09-04", t: "보류" }],
    },
    {
      id: "hero-movie", title: "맞춤 히어로 무비 199,000원 (P6)", stage: "dropped", area: "영업·가격", decision: "보류",
      owner: "회장님", since: "2026-08-31", updated: "2026-09-03",
      summary: "런칭 범위 제외 검토 중. 대체안 Ken Burns 슬라이드('kenburns' 항목).",
      why: "검증 전 무거운 제작 공정.",
      status: "보류(사장님 결정 대기).", next: "결정.", docs: [], history: [{ d: "2026-09-03", t: "보류" }],
    },
  ],
};
